//! Hand-declared gRPC client stubs for `altavista.v1.DataGatewayService` and
//! `altavista.v1.ModelProposeService`, generated by `build.rs`'s second codegen pass
//! (`tonic_build::manual`) -- see that file's own module doc for the full reasoning: this
//! crate must never generate a client for `CommandAuthorityService` (also declared in
//! `authority.proto`, alongside these two), so this pass never parses that file's text at
//! all, and instead declares only these two services' own method shapes against
//! [`av_cdm::pb`]'s already-compiled message types.
//!
//! Both `include!`s land in this one module so a call site can write
//! `crate::gateway_pb::data_gateway_service_client::DataGatewayServiceClient` and
//! `crate::gateway_pb::model_propose_service_client::ModelProposeServiceClient`, mirroring
//! how every other service crate in this workspace names its own generated `pb` module.

#![allow(clippy::all)] // generated code, not this crate's own style -- see crate::gateway_pb's own doc and every other crate's identical `pb` module.

include!(concat!(env!("OUT_DIR"), "/altavista.v1.DataGatewayService.rs"));
include!(concat!(env!("OUT_DIR"), "/altavista.v1.ModelProposeService.rs"));
