//! R3.4 (`docs/open-questions.md` question 206, `docs/aiplane-plan.md`'s round-2 declared gap):
//! the gateway proven against the A3.3 command-trail replay fixture's own kind of run
//! products -- a REAL, git-tracked `RunProducts` (`tests/fixtures/demo_command_trail.
//! runproducts.bin`) whose `events` genuinely include `EVENT_KIND_COMMAND_TRANSITION` events
//! for a command that actually went through the real `CommandAuthorityService` and the real
//! kernel, served through a REAL `DataGatewayService` over a real loopback socket (this file's
//! own `harness` module, below).
//!
//! ## What this fixture proves that `demo_measurements.runproducts.bin` could not
//!
//! `crates/av-gateway/tests/real_run_products.rs`'s own fixture
//! (`demo_measurements.runproducts.bin`) is a real `execute()` run with real trajectories,
//! events, and measurements -- but its own `events` carry no `EVENT_KIND_COMMAND_TRANSITION`
//! at all (that file's own module doc, and `docs/aiplane-plan.md`'s round-2 declared gap,
//! state this plainly: "the gateway is not yet proven against a run whose events include a
//! command trail"). This file closes that gap: `GATEWAY_SELECTOR_EVENTS` against THIS fixture
//! returns a real, five-transition command trail (`PROPOSED` -> `CHECKED` -> `AUTHORIZED` ->
//! `DISPATCHED` -> `ACKED`) for a real command id (`"safe1"`) that a real
//! `CommandAuthorityServiceImpl` and a real `av_kernel::drm::execute` run actually produced --
//! never a hand-built `Event` literal.
//!
//! ## How the fixture was produced (reproducible recipe)
//!
//! `tests/fixtures/demo_command_trail.runproducts.bin` is generated by `crates/av-run/tests/
//! command_dispatch_e2e.rs::generate_command_trail_run_products_fixture` (`#[ignore]`d) --
//! see that test's own module doc for the exact recipe (a real `CommandAuthorityService` over
//! a real loopback socket dispatches the demo attitude DRM's `"safe1"` SAFE-mode command
//! through `av_run::command_adapter::KernelCommandAdapter` into a live `av_kernel::drm::execute`
//! run of `drms/demo_attitude_command.{drm,sos}.yaml`, under the frozen `run_id`
//! `"demo-command-trail-frozen"`). Regenerate with:
//! ```text
//! export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
//! export GMAT_ROOT="/Users/probe/code/AltaVista/GMAT R2026a"
//! export CFS_MIRROR_DIR=/Users/probe/code/AltaVista/third_party/mirrors
//! cargo test -p av-run --test command_dispatch_e2e -- --ignored --nocapture generate_command_trail_run_products_fixture
//! ```
//!
//! ## Why a local, single-use harness (`mod harness`), not `tests/common/mod.rs`
//!
//! `crates/av-gateway/tests/common/mod.rs`'s own module doc states its own convention plainly:
//! a helper used by only one test binary in this crate lives in that binary directly (its own
//! example, `tests/propose_only.rs`'s `CommandAuthorityHarness`); one used by several lives in
//! `common`. No other test binary in this crate needs a bare `DataGatewayService`-only server
//! (this fixture carries no command proposal to authorize, so `ModelProposeService`/
//! `CommandAuthorityService` are not wired here at all -- this is the read path alone), so this
//! file's own harness stays local, mirroring `tests/propose_only.rs`'s identical pattern.

mod harness {
    use std::collections::BTreeMap;
    use std::sync::Arc;

    use av_gateway::catalogue::{CatalogueEntry, RunCatalogue};
    use av_gateway::counters::Counters;
    use av_gateway::gateway::{DataGatewayServiceImpl, DataGatewayServiceServer, GatewayCore};
    use av_gateway::labels::ClearanceLadder;
    use av_gateway::pb::data_gateway_service_client::DataGatewayServiceClient;
    use tokio::net::TcpListener;
    use tokio::sync::oneshot;
    use tokio_stream::wrappers::TcpListenerStream;
    use tonic::transport::{Channel, Endpoint, Server};

    /// A REAL `DataGatewayService` (`crate::harness`'s own name for [`av_gateway::gateway::
    /// DataGatewayServiceImpl`]) over a real loopback socket -- never `GatewayCore::query`
    /// called in-process, so this test genuinely exercises the gRPC wire adapter
    /// (`to_status`'s own `RefusalReason` -> `tonic::Status` mapping included), not only the
    /// core resolution logic `crates/av-gateway/tests/real_run_products.rs` already covers
    /// in-process.
    pub struct GatewayServerHarness {
        pub client: DataGatewayServiceClient<Channel>,
        pub counters: Arc<Counters>,
        shutdown_tx: Option<oneshot::Sender<()>>,
        handle: Option<tokio::task::JoinHandle<()>>,
    }

    impl GatewayServerHarness {
        pub async fn spawn(entries: BTreeMap<String, CatalogueEntry>, ladder: ClearanceLadder) -> Self {
            let counters = Arc::new(Counters::new());
            let core = Arc::new(GatewayCore::new(RunCatalogue::new(entries), ladder, counters.clone()));

            let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind an ephemeral loopback port");
            let addr = listener.local_addr().expect("local_addr");
            let incoming = TcpListenerStream::new(listener);

            let (shutdown_tx, shutdown_rx) = oneshot::channel::<()>();
            let handle = tokio::spawn(async move {
                Server::builder()
                    .add_service(DataGatewayServiceServer::new(DataGatewayServiceImpl::new(core)))
                    .serve_with_incoming_shutdown(incoming, async {
                        let _ = shutdown_rx.await;
                    })
                    .await
                    .expect("server exits cleanly");
            });

            let channel = Endpoint::from_shared(format!("http://{addr}"))
                .expect("valid endpoint URI")
                .connect()
                .await
                .expect("connect to the just-spawned DataGatewayService over its real loopback socket");
            let client = DataGatewayServiceClient::new(channel);

            Self { client, counters, shutdown_tx: Some(shutdown_tx), handle: Some(handle) }
        }

        pub async fn shutdown(mut self) {
            if let Some(tx) = self.shutdown_tx.take() {
                let _ = tx.send(());
            }
            if let Some(handle) = self.handle.take() {
                let _ = handle.await;
            }
        }
    }
}

use std::collections::BTreeMap;

use av_cdm::pb::{EventKind, GatewayQueryRequest, GatewaySelector, Label, RunIdentity};
use av_gateway::catalogue::CatalogueEntry;
use av_gateway::labels::ClearanceLadder;
use harness::GatewayServerHarness;
use prost::Message as _;
use tonic::Code;

const RUN_ID: &str = "run-command-trail";
const FIXTURE_RUN_ID: &str = "demo-command-trail-frozen";

fn fixture_bytes() -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/demo_command_trail.runproducts.bin");
    std::fs::read(&path).unwrap_or_else(|e| panic!("read real RunProducts fixture at {}: {e}", path.display()))
}

fn catalogue_and_ladder(marking: &str) -> (BTreeMap<String, CatalogueEntry>, ClearanceLadder) {
    let mut entries = BTreeMap::new();
    entries.insert(RUN_ID.to_string(), CatalogueEntry::from_raw_bytes(Label { marking: marking.to_string(), caveats: vec![] }, fixture_bytes()));
    let ladder = ClearanceLadder::new(vec!["UNCLASSIFIED".to_string(), "CUI".to_string(), "SECRET".to_string()]);
    (entries, ladder)
}

fn events_request(clearance: &str) -> GatewayQueryRequest {
    GatewayQueryRequest {
        run: Some(RunIdentity { run_id: RUN_ID.to_string(), config_hash: String::new() }),
        caller_clearance: clearance.to_string(),
        selector: GatewaySelector::Events as i32,
        caller_supplied_products_uri: String::new(),
    }
}

/// Sanity: the fixture really is what its own generator (`crates/av-run/tests/
/// command_dispatch_e2e.rs::generate_command_trail_run_products_fixture`) documents -- decoded
/// directly (not through the gateway) so a wrong or stale committed fixture would fail here
/// before this file's own gateway assertions could be blamed for it.
#[test]
fn the_fixture_is_the_real_command_trail_run_and_carries_the_expected_transitions() {
    let rp = av_cdm::pb::RunProducts::decode(fixture_bytes().as_slice()).expect("fixture decodes as RunProducts");
    assert_eq!(rp.run_id, FIXTURE_RUN_ID);
    assert!(!rp.trajectories.is_empty());
    assert!(!rp.events.is_empty());

    let transitions: Vec<_> = rp.events.iter().filter(|e| e.kind == EventKind::CommandTransition as i32 && e.reference_id == "safe1").collect();
    let states: Vec<&str> = transitions.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(states, vec!["COMMAND_STATE_PROPOSED", "COMMAND_STATE_CHECKED", "COMMAND_STATE_AUTHORIZED", "COMMAND_STATE_DISPATCHED", "COMMAND_STATE_ACKED"], "{transitions:#?}");
    let epochs: Vec<i64> = transitions.iter().map(|e| e.tai_ns).collect();
    assert_eq!(epochs, vec![1_767_225_637_000_000_000, 1_767_225_637_000_000_001, 1_767_225_637_000_000_002, 1_767_225_647_000_000_000, 1_767_225_648_400_000_000], "the fixture's own real, measured epochs (see this file's own module doc's generator output) -- a fixture regenerated from a changed setup would disagree here, loudly");
}

/// The command-trail fixture, served through a REAL `DataGatewayService` over a real loopback
/// socket: `GATEWAY_SELECTOR_EVENTS` returns the identical five-transition command trail for
/// `"safe1"`, in the gateway's own documented sorted order (`crate::drm::events::
/// epoch_id_order`'s `(tai_ns, id)` -- `crates/av-kernel/src/drm/events.rs`'s own doc comment;
/// the gateway itself never re-sorts, it returns `RunProducts.events` exactly as the real
/// kernel run wrote them, already in that order).
#[tokio::test]
async fn the_gateway_serves_the_real_command_trail_over_a_real_socket_in_sorted_order() {
    let (entries, ladder) = catalogue_and_ladder("CUI");
    let mut harness = GatewayServerHarness::spawn(entries, ladder).await;

    let resp = harness.client.query(events_request("CUI")).await.expect("EVENTS query over the real command-trail fixture").into_inner();
    assert!(!resp.events.is_empty());

    // Sorted order, over the WHOLE response (not just the filtered subset below) -- proves the
    // gateway is not merely returning a coincidentally-sorted five-element slice.
    let mut prev: Option<(i64, &str)> = None;
    for e in &resp.events {
        let key = (e.tai_ns, e.id.as_str());
        if let Some(p) = prev {
            assert!(p <= key, "events must be non-decreasing in (tai_ns, id) order; {p:?} came before {key:?}");
        }
        prev = Some(key);
    }

    // The specific command trail this fixture actually contains: name the states and the
    // command id, never merely "at least one event" (this task's own instruction).
    let transitions: Vec<_> = resp.events.iter().filter(|e| e.kind == EventKind::CommandTransition as i32 && e.reference_id == "safe1").collect();
    let states: Vec<&str> = transitions.iter().map(|e| e.name.as_str()).collect();
    assert_eq!(states, vec!["COMMAND_STATE_PROPOSED", "COMMAND_STATE_CHECKED", "COMMAND_STATE_AUTHORIZED", "COMMAND_STATE_DISPATCHED", "COMMAND_STATE_ACKED"], "{transitions:#?}");
    assert_eq!(transitions[0].tai_ns, 1_767_225_637_000_000_000, "PROPOSED");
    assert_eq!(transitions[1].tai_ns, 1_767_225_637_000_000_001, "CHECKED");
    assert_eq!(transitions[2].tai_ns, 1_767_225_637_000_000_002, "AUTHORIZED");
    assert_eq!(transitions[3].tai_ns, 1_767_225_647_000_000_000, "DISPATCHED");
    assert_eq!(transitions[4].tai_ns, 1_767_225_648_400_000_000, "ACKED");
    for t in &transitions {
        assert_eq!(t.entity_id, "controller", "the demo attitude DRM's own mode-command target");
    }

    assert_eq!(harness.counters.get("gateway_product_missing_on_host"), 0, "a genuinely EVENTS-populated fixture must never be refused as missing on this host");
    harness.shutdown().await;
}

/// D2's label enforcement applies to this fixture exactly like any other real fixture
/// (`crates/av-gateway/tests/real_run_products.rs`'s own module doc line: "the same real
/// fixture" -- the point of this whole task is that the command-trail fixture is not a special
/// case): a caller below the fixture's own CUI label is refused `PERMISSION_DENIED` over the
/// real gRPC surface, and the refusal is counted.
#[tokio::test]
async fn a_caller_below_the_fixtures_own_clearance_is_refused_over_the_real_socket_and_counted() {
    let (entries, ladder) = catalogue_and_ladder("CUI");
    let mut harness = GatewayServerHarness::spawn(entries, ladder).await;

    let err = harness.client.query(events_request("UNCLASSIFIED")).await.expect_err("a caller below the fixture's own CUI label must be refused");
    assert_eq!(err.code(), Code::PermissionDenied, "{err:?}");
    assert_eq!(harness.counters.get("label_over_clearance"), 1, "the refusal must be counted (ADR-004: everything rejected is counted)");

    // The identical query, at the fixture's own clearance, still succeeds against this same
    // running server -- proves the refusal above was genuinely about the caller's clearance,
    // not a broken server or a malformed request this fixture happens to trigger.
    let ok = harness.client.query(events_request("CUI")).await.expect("the identical query at the fixture's own clearance must succeed");
    assert!(!ok.into_inner().events.is_empty());

    harness.shutdown().await;
}
