//! M18.3's headline test (`docs/open-questions.md` question 126): a SIGNAL-commanded `Cd`
//! change mid-run, applied through `gmat_sys::model::GmatModel::step_with_ports` (this task's
//! own new override -- see that method's doc comment), genuinely alters a propagated drag arc,
//! pinned against a real GMAT script + `ReportFile` reference
//! (`goldens/gmat_port_cd_command.json`, generated by `goldens/gen_gmat_port_cd_command.py`
//! exactly the way `goldens/gen_leo_1day_rmag.py` already does it in this repository -- a
//! script run through `gmat.LoadScript`/`gmat.RunScript`, `SolverIterations = Current`, never
//! `Execute()` through the object API and never `gmat.SaveScript`, both of which this
//! repository has already documented as unusable for this purpose).
//!
//! **The trap this test exists to avoid.** `drms/demo_two_instance.system.yaml`'s own force
//! model (JGM2 8x8 + Sun/Moon point masses) has no atmospheric drag, so a `Cd` change there is
//! physically inert -- `crates/av-kernel/tests/demo_two_instance.rs::
//! demo_two_instance_signal_port_delivers_a_real_gmat_to_gmat_command` proves the SIGNAL
//! mechanism itself delivers a real value end to end, but deliberately cannot prove Cd *matters*
//! physically. This file builds a separate, test-only, drag-inclusive force model (`DragForce` +
//! `JacchiaRoberts` atmosphere, the same choice `goldens/gen_leo_1day.py --drag-srp` already
//! uses for `leo_1day_jgm2_8x8_sunmoon_drag_srp.json`, at the same ~250 km-altitude LEO) so `Cd`
//! has a real, measured effect -- see `baseline_arc_and_commanded_arc_genuinely_differ` below for
//! the actual number, and the golden's own `measured_arc_difference_commanded_vs_baseline_m`
//! field for the independent Python-side measurement it is checked against.
//!
//! **M19.3 additions (`docs/open-questions.md` question 130).** This fixture is reused, not
//! rebuilt, for the two required tests question 130 needs a drag-inclusive (physically
//! meaningful) command stream for:
//! `step_with_ports_reports_exactly_the_expected_applied_commands` (the M18.3 commanded-Cd run
//! reports exactly the expected `av_dynamics::AppliedCommand`s -- count and attributes) and
//! `commanded_and_baseline_trajectories_differ_with_an_equal_dynamics_hash` (a differing command
//! stream produces different trajectories while `describe().settings_hash` -- the value that
//! becomes `TrajectorySegment.dynamics_hash` downstream -- stays equal, both halves asserted
//! together).

use std::collections::BTreeMap;
use std::path::PathBuf;

use av_dynamics::{decode_signal, encode_signal, AppliedCommand, DynamicsModel, Inbox};
use gmat_sys::model::{GmatModel, GmatModelInfo, GmatPortConfig, OUTPUT_CD, OUTPUT_RMAG};
use gmat_sys::Gmat;
use serde::Deserialize;

const CD_BEFORE: f64 = 2.2;
const CD_AFTER: f64 = 4.4;
const COMMAND_PORT: &str = "cd_cmd";
const HALF_DURATION_NS: i64 = 3600 * 1_000_000_000;

#[derive(Deserialize)]
struct RowDict {
    x_km: f64,
    y_km: f64,
    z_km: f64,
}

#[derive(Deserialize)]
struct Commanded {
    final_row: RowDict,
}

#[derive(Deserialize)]
struct Baseline {
    final_row: RowDict,
}

#[derive(Deserialize)]
struct Golden {
    tolerance_m: f64,
    commanded: Commanded,
    baseline_uncommanded: Baseline,
    measured_arc_difference_commanded_vs_baseline_m: f64,
}

fn golden() -> Golden {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../goldens/gmat_port_cd_command.json");
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("reading {path:?}: {e}"))).expect("gmat_port_cd_command.json parses")
}

/// Build a fresh drag-inclusive `GmatModel` under a unique GMAT object-name prefix (`tag`) --
/// `crates/gmat-sys/tests/leo_golden.rs::two_models_in_one_process_do_not_interfere` already
/// proves distinct-named objects coexist safely in one process; this mirrors that pattern
/// exactly, just with a `DragForce` + `JacchiaRoberts` atmosphere added, matching
/// `goldens/gen_gmat_port_cd_command.py`'s own script field-for-field (SMA 6628 km, the same
/// ~250 km-altitude orbit `goldens/gen_leo_1day.py --drag-srp` uses, JGM2 8x8 + Luna/Sun, no
/// SRP -- SRP does not depend on Cd, so it is left out to keep this fixture focused).
fn build_model(gmat: &Gmat, tag: &str, ports: GmatPortConfig) -> GmatModel {
    let sat = gmat.construct("Spacecraft", &format!("{tag}Sat")).unwrap();
    sat.set_str("DateFormat", "UTCGregorian").unwrap();
    sat.set_str("Epoch", "01 Jan 2026 00:00:00.000").unwrap();
    sat.set_str("CoordinateSystem", "EarthMJ2000Eq").unwrap();
    sat.set_str("DisplayStateType", "Keplerian").unwrap();
    sat.set_real("SMA", 6628.0).unwrap();
    sat.set_real("ECC", 0.001).unwrap();
    sat.set_real("INC", 51.6).unwrap();
    sat.set_real("RAAN", 30.0).unwrap();
    sat.set_real("AOP", 0.0).unwrap();
    sat.set_real("TA", 0.0).unwrap();
    sat.set_real("DryMass", 500.0).unwrap();
    sat.set_real("Cd", CD_BEFORE).unwrap();
    sat.set_real("Cr", 1.8).unwrap();
    sat.set_real("DragArea", 5.0).unwrap();
    sat.set_real("SRPArea", 5.0).unwrap();

    let fm = gmat.construct("ForceModel", &format!("{tag}FM")).unwrap();
    fm.set_str("CentralBody", "Earth").unwrap();
    let grav = gmat.construct("GravityField", &format!("{tag}Grav")).unwrap();
    grav.set_str("BodyName", "Earth").unwrap();
    grav.set_str("PotentialFile", "JGM2.cof").unwrap();
    grav.set_int("Degree", 8).unwrap();
    grav.set_int("Order", 8).unwrap();
    fm.add_force(&grav).unwrap();
    for (i, body) in ["Luna", "Sun"].into_iter().enumerate() {
        let pm = gmat.construct("PointMassForce", &format!("{tag}Pm{i}")).unwrap();
        pm.set_str("BodyName", body).unwrap();
        fm.add_force(&pm).unwrap();
    }
    let drag = gmat.construct("DragForce", &format!("{tag}Drag")).unwrap();
    drag.set_str("AtmosphereModel", "JacchiaRoberts").unwrap();
    let atmos = gmat.construct("JacchiaRoberts", &format!("{tag}Atmos")).unwrap();
    drag.set_reference(&atmos).unwrap();
    fm.add_force(&drag).unwrap();

    gmat.initialize().unwrap();
    let derivative_model = gmat.derivative_model(&fm, &sat).expect("derivative model");
    let info = GmatModelInfo {
        id: format!("gmat.test.{tag}"),
        version: "R2026a".to_string(),
        state_space_id: "gmat.orbital.cartesian6".to_string(),
        frame_id: "EarthMJ2000Eq".to_string(),
        goldens: vec![],
        has_relativistic_correction: false,
    };
    GmatModel::new(derivative_model, info, &BTreeMap::new(), false).with_ports(ports)
}

/// Drive `model` through two 3600 s `step_with_ports` calls -- matching
/// `goldens/gen_gmat_port_cd_command.py`'s own two `Propagate GoldenProp(Golden)
/// {Golden.ElapsedSecs = 3600}` statements exactly, one call per stage. `commanded_cd`, when
/// `Some`, is delivered as a SIGNAL message on [`COMMAND_PORT`] at the start of the *second*
/// stage only -- the same "Cd assignment happens once, between the two Propagate statements"
/// structure the script uses. Returns the final SI state (metres/metres-per-second) alongside
/// each stage's own `Vec<AppliedCommand>` (question 130, M19.3) -- stage 1 must always be
/// empty (no message is ever delivered that early); stage 2 is non-empty exactly when
/// `commanded_cd` is `Some`.
fn run_two_stage(model: &GmatModel, commanded_cd: Option<f64>) -> ([f64; 6], Vec<AppliedCommand>, Vec<AppliedCommand>) {
    let x0 = model.initial_state_si().expect("initial state");
    let t0_tai_ns = model.epoch_tai_ns();

    let (stage1, _outbox1, applied1) = model.step_with_ports(&x0, t0_tai_ns, &[], HALF_DURATION_NS, &Inbox::empty()).expect("stage 1 step");

    let inbox2 = match commanded_cd {
        Some(cd) => Inbox::new(vec![av_cdm::pb::PortMessage { port: COMMAND_PORT.to_string(), tai_ns: stage1.t_tai_ns, payload: encode_signal(cd) }]),
        None => Inbox::empty(),
    };
    let (stage2, _outbox2, applied2) = model.step_with_ports(&stage1.state, stage1.t_tai_ns, &[], HALF_DURATION_NS, &inbox2).expect("stage 2 step");

    (stage2.state.try_into().expect("6-element state"), applied1, applied2)
}

fn dist_m(a: &[f64; 6], b_km: [f64; 3]) -> f64 {
    let b_m = av_cdm::units::state_km_to_m([b_km[0], b_km[1], b_km[2], 0.0, 0.0, 0.0]);
    (0..3).map(|i| (a[i] - b_m[i]).powi(2)).sum::<f64>().sqrt()
}

/// **The headline test.** A SIGNAL message carrying `Cd = 4.4`, delivered through `Inbox`/
/// `GmatModel::step_with_ports`'s `consume` path at the start of the second 3600 s stage,
/// changes the propagated final position by hundreds of metres relative to a structurally
/// identical run that never received the message -- and that commanded arc matches a genuine
/// GMAT script (`gmat.LoadScript`/`gmat.RunScript`, `ReportFile`, `SolverIterations = Current`)
/// that applies the identical `Cd` reassignment at the identical epoch through its own mission
/// sequence, within tolerance.
///
/// **Fails against:** `GmatModel::step_with_ports` not overriding the trait default (the
/// `consume` branch would never run at all -- `Cd` would stay 2.2 throughout, and the commanded
/// arc would be bit-identical to the baseline, not merely close -- see the companion test
/// `baseline_arc_and_commanded_arc_genuinely_differ` for that exact check); `DerivativeModel::
/// set_real_parameter` writing the wrong field, or writing before `GmatModel::step` has already
/// synced the propagated state and epoch (either would leave the commanded arc very far from
/// both the baseline and the golden, well outside `tolerance_m`); or a `step_with_ports`
/// implementation that decodes/consumes the message *after* stepping (the command would apply
/// one stage too late, and the commanded arc would equal the baseline's stage-1 state
/// re-propagated with the OLD Cd for stage 2 -- still measurably different from this golden).
#[test]
fn signal_commanded_cd_change_matches_a_genuine_gmat_script_reference() {
    let _engine = gmat_sys::engine_lock();
    let g = golden();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");

    let commanded_model = build_model(&gmat, "PortCmd", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });
    let (commanded_final, _applied1, _applied2) = run_two_stage(&commanded_model, Some(CD_AFTER));

    let dr = dist_m(&commanded_final, [g.commanded.final_row.x_km, g.commanded.final_row.y_km, g.commanded.final_row.z_km]);
    eprintln!("[gmat_port_cd_command] commanded arc vs. genuine GMAT script reference: |dr| = {dr:.4} m (tolerance {} m)", g.tolerance_m);
    assert!(dr < g.tolerance_m, "SIGNAL-commanded Cd arc disagrees with the genuine GMAT script reference by {dr} m (tolerance {} m)", g.tolerance_m);
}

/// **The anti-vacuous-test check the brief explicitly requires**: measures that the commanded
/// (`Cd` doubled mid-run) and baseline (uncommanded, `Cd` left at 2.2 throughout) arcs actually
/// differ, and by a physically sensible amount -- not the bit-identical arcs a broken
/// `step_with_ports` (one that silently ignores `inbox`, e.g. reverted to the trait default)
/// would produce. Cross-checked against `goldens/gen_gmat_port_cd_command.py`'s own independent
/// measurement of the identical baseline-vs-commanded difference through a real GMAT script (not
/// merely "greater than zero" -- the two numbers must roughly agree, since both are measuring
/// the same physical effect through two different integrators over the same GMAT-derivatives
/// force model).
#[test]
fn baseline_arc_and_commanded_arc_genuinely_differ() {
    let _engine = gmat_sys::engine_lock();
    let g = golden();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");

    let baseline_model = build_model(&gmat, "PortBase", GmatPortConfig::default());
    let (baseline_final, _applied1, _applied2) = run_two_stage(&baseline_model, None);

    let commanded_model = build_model(&gmat, "PortCmd2", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });
    let (commanded_final, _applied1_cmd, _applied2_cmd) = run_two_stage(&commanded_model, Some(CD_AFTER));

    // The baseline arc itself also matches the golden's own independently-run, structurally
    // identical (no-op "command") baseline -- confirms this test's own `run_two_stage(...,
    // None)` path is not just "differs from commanded" but is the *correct* uncommanded arc.
    let baseline_dr = dist_m(&baseline_final, [g.baseline_uncommanded.final_row.x_km, g.baseline_uncommanded.final_row.y_km, g.baseline_uncommanded.final_row.z_km]);
    eprintln!("[gmat_port_cd_command] baseline arc vs. genuine GMAT script reference: |dr| = {baseline_dr:.4} m (tolerance {} m)", g.tolerance_m);
    assert!(baseline_dr < g.tolerance_m, "uncommanded baseline arc disagrees with the genuine GMAT script reference by {baseline_dr} m (tolerance {} m)", g.tolerance_m);

    let arc_difference_m = (0..3).map(|i| (commanded_final[i] - baseline_final[i]).powi(2)).sum::<f64>().sqrt();
    eprintln!(
        "[gmat_port_cd_command] measured |commanded - baseline| = {arc_difference_m:.3} m (golden's own independent measurement: {} m)",
        g.measured_arc_difference_commanded_vs_baseline_m
    );

    // Must be a real, physically sensible effect -- not floating-point noise, and not so large
    // it suggests a different bug (an unbounded blow-up, a units error, ...). 1 m as a floor
    // and 1e5 m (100 km, still tiny next to the ~6900 km orbital radius) as a ceiling comfortably
    // bracket the measured hundreds-of-metres effect on both sides.
    assert!(arc_difference_m > 1.0, "commanded and baseline arcs must differ by a physically real amount, not floating-point noise; got {arc_difference_m} m");
    assert!(arc_difference_m < 1.0e5, "commanded/baseline difference of {arc_difference_m} m is implausibly large for a Cd change over one hour of drag -- suspect a units or wiring bug, not a real drag effect");

    // Cross-checked against the independent Python/GMAT-script measurement of the same effect.
    let cross_check_delta = (arc_difference_m - g.measured_arc_difference_commanded_vs_baseline_m).abs();
    assert!(
        cross_check_delta < 50.0,
        "this crate's own measured commanded-vs-baseline difference ({arc_difference_m} m) disagrees with the golden's independent GMAT-script measurement ({} m) by {cross_check_delta} m -- too large to both be measuring the same effect",
        g.measured_arc_difference_commanded_vs_baseline_m
    );
}

/// The `emit` half of `GmatModel::step_with_ports`, checked in isolation and without needing
/// the golden fixture at all: whatever `GmatModel::step` wrote into `StepResult.outputs` under
/// the declared `output_key` is sent, byte-identical (round-tripped through
/// `av_dynamics::encode_signal`/`decode_signal`), as a SIGNAL message on the declared port, at
/// the step's own result epoch. Fails against: `GmatPortConfig::emit` being ignored (empty
/// `Outbox`, the trait's own default); the wrong output key being read (`rmag` instead of `cd`
/// or vice versa); or the emitted value not matching `StepResult.outputs` exactly (a re-encoding
/// or unit-conversion bug between the two).
#[test]
fn emit_sends_the_models_own_named_output_as_a_signal_message() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");
    let model = build_model(&gmat, "PortEmit", GmatPortConfig { emit: Some(("rmag_out".to_string(), OUTPUT_RMAG.to_string())), consume: None });

    let x0 = model.initial_state_si().unwrap();
    let t0 = model.epoch_tai_ns();
    let (result, outbox, applied) = model.step_with_ports(&x0, t0, &[], HALF_DURATION_NS, &Inbox::empty()).expect("step");

    let sent = outbox.messages();
    assert_eq!(sent.len(), 1, "exactly one SIGNAL message must be emitted per step when emit is configured");
    assert_eq!(sent[0].port, "rmag_out");
    assert_eq!(sent[0].tai_ns, result.t_tai_ns);
    let decoded = decode_signal(&sent[0].payload).expect("a SIGNAL payload decodes back to f64");
    assert_eq!(decoded, *result.outputs.get(OUTPUT_RMAG).expect("GmatModel::step always populates OUTPUT_RMAG"));
    assert!(applied.is_empty(), "no `consume` is configured on this model, so nothing was ever applied -- emit alone must report no AppliedCommand");

    // A model with no `emit` configured at all (the overwhelming majority) still returns an
    // empty Outbox, exactly the trait's own default behaviour for a model that opts into
    // nothing -- proves `with_ports(GmatPortConfig::default())` is truly inert.
    let plain_model = build_model(&gmat, "PortPlain", GmatPortConfig::default());
    let x0_plain = plain_model.initial_state_si().unwrap();
    let t0_plain = plain_model.epoch_tai_ns();
    let (_result_plain, outbox_plain, applied_plain) = plain_model.step_with_ports(&x0_plain, t0_plain, &[], HALF_DURATION_NS, &Inbox::empty()).expect("step");
    assert!(outbox_plain.is_empty(), "a GmatModel with no port wiring configured must emit nothing");
    assert!(applied_plain.is_empty(), "a GmatModel with no port wiring configured must apply nothing");
    let _ = OUTPUT_CD; // documents the sibling output key exists and is exported, for readers of this file
}

// ==========================================================================================
// M19.3 (`docs/open-questions.md` question 130): applied commands are surfaced out of
// `step_with_ports` so they can be recorded as `EVENT_KIND_PORT_COMMAND` CDM events, and
// `dynamics_hash` (`describe().settings_hash`) stays the configuration hash regardless of what
// a run's own command stream did.
// ==========================================================================================

/// **Required test 1**: the M18.3 commanded-Cd run reports EXACTLY the expected applied
/// commands -- the count and every attribute, not merely "some command was applied." Fails
/// against: `GmatModel::step_with_ports` reporting an `AppliedCommand` even when nothing was
/// actually decoded/written (e.g. unconditionally on every call with `consume` configured,
/// regardless of whether a message was present); reporting the wrong `port`/`field`/`value`/
/// `applied_tai_ns`; or reporting one for the *uncommanded* run (no message is ever delivered
/// there at all -- "applied" is the bar, question 130, not "wired for it").
#[test]
fn step_with_ports_reports_exactly_the_expected_applied_commands() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");

    // Uncommanded: neither stage ever has a message on the command port at all.
    let uncommanded_model = build_model(&gmat, "PortApplyNone", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });
    let (_final_uncommanded, applied1_none, applied2_none) = run_two_stage(&uncommanded_model, None);
    assert!(applied1_none.is_empty(), "stage 1 never has a message on the command port");
    assert!(applied2_none.is_empty(), "no message was ever delivered in stage 2 of the uncommanded run either -- nothing to apply, so nothing must be reported");

    // Commanded: stage 1 is still empty (no message has been sent yet -- `run_two_stage` only
    // ever delivers `commanded_cd` at the start of stage 2); stage 2 must report EXACTLY one
    // applied command, with every attribute the CDM event this feeds needs.
    let commanded_model = build_model(&gmat, "PortApplyOne", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });
    let t0_tai_ns = commanded_model.epoch_tai_ns();
    let (_final_commanded, applied1, applied2) = run_two_stage(&commanded_model, Some(CD_AFTER));
    assert!(applied1.is_empty(), "stage 1 never has a message on the command port, even on the commanded run");
    assert_eq!(applied2.len(), 1, "stage 2 must report EXACTLY one applied command -- not zero (the command was dropped) and not more than one (double-application)");
    let cmd = &applied2[0];
    assert_eq!(cmd.port, COMMAND_PORT, "the reported port must be the one the message actually arrived on");
    assert_eq!(cmd.field, "Cd", "the reported field must be GmatPortConfig::consume's own declared field name");
    assert_eq!(cmd.value, CD_AFTER, "the reported value must be exactly the decoded SIGNAL payload, not some other reading of Cd");
    assert_eq!(
        cmd.applied_tai_ns,
        t0_tai_ns + HALF_DURATION_NS,
        "applied_tai_ns must be stage 2's own START epoch (stage 1's end) -- the instant the commanded value actually takes effect -- not stage 2's END epoch or the message's own delivery tai_ns"
    );
}

/// **Required test 3**: a command stream that differs (the uncommanded baseline vs. the
/// Cd-doubled commanded run -- the same drag-inclusive pair
/// `baseline_arc_and_commanded_arc_genuinely_differ` already measures) produces DIFFERENT
/// trajectories with an EQUAL `dynamics_hash`, asserted together in this one test -- the exact
/// invariant question 130 establishes ("equal `dynamics_hash` means equal configuration; equal
/// configuration plus equal command events means equal dynamics") is not actually checked
/// unless both halves are asserted in the same place. `describe().settings_hash` is the literal
/// value `av-kernel`'s `crate::drm::executor::finish_trajectory` forwards, unchanged, into
/// `TrajectorySegment.dynamics_hash` -- checking it here checks the real field, not an
/// approximation of it.
///
/// Fails against: an implementation that (wrongly, against the lead's explicit decision) folds
/// the commanded value into the settings hash -- the two models below, built from an identical
/// (empty) settings map but with different `GmatPortConfig`/command streams, would then
/// disagree; or a `step_with_ports` regression that makes the command a no-op, which would
/// leave the two trajectories bit-identical and fail this test's own vacuousness guard (the
/// same `> 1.0` m floor `baseline_arc_and_commanded_arc_genuinely_differ` already uses).
#[test]
fn commanded_and_baseline_trajectories_differ_with_an_equal_dynamics_hash() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");

    // Both built from the IDENTICAL (empty) settings map `build_model` always passes to
    // `GmatModel::new` -- the same configuration either way. Only the COMMAND STREAM differs.
    let baseline_model = build_model(&gmat, "PortHashBase", GmatPortConfig::default());
    let commanded_model = build_model(&gmat, "PortHashCmd", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });

    let baseline_hash = baseline_model.describe().settings_hash;
    let commanded_hash = commanded_model.describe().settings_hash;

    let (baseline_final, _b1, _b2) = run_two_stage(&baseline_model, None);
    let (commanded_final, _c1, applied2) = run_two_stage(&commanded_model, Some(CD_AFTER));
    assert_eq!(applied2.len(), 1, "sanity: the commanded run really did apply a command (otherwise the first half below would be vacuous)");

    // Half 1: the trajectories genuinely differ.
    let arc_difference_m = (0..3).map(|i| (commanded_final[i] - baseline_final[i]).powi(2)).sum::<f64>().sqrt();
    eprintln!("[gmat_port_cd_command] commanded vs. baseline arc difference: {arc_difference_m:.3} m");
    assert!(arc_difference_m > 1.0, "commanded and baseline trajectories must differ by a physically real amount, not floating-point noise; got {arc_difference_m} m");

    // Half 2: `dynamics_hash` (describe().settings_hash) is EQUAL regardless -- asserted
    // explicitly, not implied by the first half.
    assert_eq!(
        baseline_hash, commanded_hash,
        "dynamics_hash must stay the configuration hash (question 130): two models built from an identical settings map must hash identically regardless of what SIGNAL command stream either one later applies"
    );

    eprintln!("[gmat_port_cd_command] dynamics_hash equal ({baseline_hash}) while trajectories differ by {arc_difference_m:.3} m -- question 130's invariant holds");
}

// ==========================================================================================
// M20.3 (`docs/open-questions.md` question 137, closing the lead's M19.3 finding: "a
// continuously commanded parameter emits one event per step" -- 71,999 events over a 2 h, 10 Hz
// stream). `GmatModel::step_with_ports` now records an `AppliedCommand` only when the newly
// applied value differs (bit-exact, never a tolerance) from the last value it actually applied
// for that field, or on the first application ever -- the underlying `set_real_parameter` write
// itself still happens unconditionally, every step, unchanged.
// ==========================================================================================

/// Drive `model` through `commands.len()` back-to-back `stage_duration_ns` stages, delivering
/// `commands[i]` (when `Some`) as a single SIGNAL message on [`COMMAND_PORT`] at the START of
/// stage `i` -- unlike [`run_two_stage`] (which only ever delivers one message, at a fixed
/// stage), this lets a test hand-pick an arbitrary sequence of commanded values, including
/// deliberate exact repeats, so the expected count of *recorded* applications (as opposed to
/// messages delivered) is known in advance rather than inferred from a physically-varying
/// value like RMAG. Returns each stage's own `Vec<AppliedCommand>`, index-parallel to
/// `commands`.
fn run_n_stages(model: &GmatModel, stage_duration_ns: i64, commands: &[Option<f64>]) -> Vec<Vec<AppliedCommand>> {
    let mut state = model.initial_state_si().expect("initial state");
    let mut t_tai_ns = model.epoch_tai_ns();
    let mut per_stage = Vec::with_capacity(commands.len());
    for cmd in commands {
        let inbox = match cmd {
            Some(value) => Inbox::new(vec![av_cdm::pb::PortMessage { port: COMMAND_PORT.to_string(), tai_ns: t_tai_ns, payload: encode_signal(*value) }]),
            None => Inbox::empty(),
        };
        let (result, _outbox, applied) = model.step_with_ports(&state, t_tai_ns, &[], stage_duration_ns, &inbox).expect("step");
        state = result.state.clone().try_into().expect("6-element state");
        t_tai_ns = result.t_tai_ns;
        per_stage.push(applied);
    }
    per_stage
}

/// **Required test: the exact event count for a stream with a KNOWN number of changes.**
/// Six stages, five delivered messages, and exactly TWO genuine changes (a first application at
/// stage 2, then a real value change at stage 5) -- everything else is either no message at all
/// (stage 1) or an exact repeat of the last applied value (stages 3, 4, 6). Physics is
/// irrelevant to this test (short 60 s stages, not the golden's own 3600 s halves), only the
/// applied-command bookkeeping is.
///
/// **Fails against:** the pre-M20.3 (`docs/open-questions.md` question 130, M19.3)
/// record-every-application behaviour, which would report an `AppliedCommand` for every one of
/// the five delivered messages (5, not 2) -- a bound like "fewer than 5" would not catch a
/// half-fixed implementation (e.g. one that dedupes consecutive stages 3-4 but not stage 6
/// against stage 5's own value), which is exactly why every stage is asserted individually
/// below, not merely the final total.
#[test]
fn step_with_ports_records_only_the_first_application_and_genuine_changes_in_a_controlled_command_stream() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");
    let model = build_model(&gmat, "PortChangeOnlyRate", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });

    const STAGE_NS: i64 = 60 * 1_000_000_000;
    // stage:      1     2         3         4         5         6
    let commands = [None, Some(3.0), Some(3.0), Some(3.0), Some(5.0), Some(5.0)];
    let applied = run_n_stages(&model, STAGE_NS, &commands);

    assert!(applied[0].is_empty(), "stage 1: no message was ever delivered -- nothing to apply, nothing to report");
    assert_eq!(applied[1].len(), 1, "stage 2: the FIRST application of Cd ever on this instance must always emit");
    assert_eq!(applied[1][0].value, 3.0);
    assert!(applied[2].is_empty(), "stage 3: value (3.0) exactly repeats the last applied value -- must emit nothing");
    assert!(applied[3].is_empty(), "stage 4: value (3.0) still repeats -- must emit nothing on the SECOND repeat too, not just the first");
    assert_eq!(applied[4].len(), 1, "stage 5: value genuinely changes (3.0 -> 5.0) -- must emit");
    assert_eq!(applied[4][0].value, 5.0);
    assert!(applied[5].is_empty(), "stage 6: value (5.0) exactly repeats the new last applied value -- must emit nothing");

    let total: usize = applied.iter().map(Vec::len).sum();
    assert_eq!(total, 2, "exactly 2 of the 5 delivered commands are new or changed; record-every-application (the pre-M20.3 behaviour) would report 5 here, not 2");
}

/// **Required test: a repeated identical command emits no event after the first.** A minimal,
/// two-stage version of the controlled-stream test above, isolated so its own failure message
/// is unambiguous. Fails against: an implementation that records every write
/// `set_real_parameter` performs, regardless of whether the value actually changed.
#[test]
fn step_with_ports_suppresses_a_repeated_identical_command_after_the_first_application() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");
    let model = build_model(&gmat, "PortChangeOnlyRepeat", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });

    let applied = run_n_stages(&model, 60 * 1_000_000_000, &[Some(CD_AFTER), Some(CD_AFTER)]);
    assert_eq!(applied[0].len(), 1, "the first application must emit");
    assert_eq!(applied[0][0].value, CD_AFTER);
    assert!(applied[1].is_empty(), "an exact repeat of the immediately preceding applied value must emit nothing");
}

/// **Required test: the first application always emits, even when its value happens to equal
/// the parameter's configured default.** `build_model` configures the spacecraft's own `Cd` at
/// `CD_BEFORE` (2.2) before any command is ever consumed -- commanding exactly that same value
/// as the very FIRST message this instance ever receives must still emit. Question 137's "the
/// first application always does" is unconditional: it does not carve out an exception for a
/// commanded value that happens to match whatever the spec already configured.
///
/// **Fails against:** an implementation that seeds `last_applied` from the model's own
/// construction-time configuration (or from reading `Cd` back via `real_parameter` before ever
/// consuming a message) instead of leaving it genuinely empty until a real SIGNAL command is
/// actually applied -- such an implementation would judge this command "unchanged" and wrongly
/// suppress it.
#[test]
fn step_with_ports_the_first_application_emits_even_when_its_value_equals_the_configured_default() {
    let _engine = gmat_sys::engine_lock();
    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");
    let model = build_model(&gmat, "PortChangeOnlyDefault", GmatPortConfig { consume: Some((COMMAND_PORT.to_string(), "Cd".to_string())), emit: None });

    let applied = run_n_stages(&model, 60 * 1_000_000_000, &[Some(CD_BEFORE)]);
    assert_eq!(applied[0].len(), 1, "the first application must emit even though its value ({CD_BEFORE}) equals the spacecraft's own configured Cd default");
    assert_eq!(applied[0][0].value, CD_BEFORE);
}
