//! M1.4: can the 42-state STM path be driven through `ODEModel::GetDerivatives` from Rust?
//! (ADR-002 amendment: "The covariance path (`PropagateSTM`, 42-state) is the next spike.")
//!
//! `derivative_model_with_stm` asks the `PropagationStateManager` for the spacecraft's STM
//! before `BuildState()` (`PropagationStateManager::SetProperty("STM", spacecraft)`, per
//! GMAT_API_Cookbook's "STM and Covariance Propagation" chapter), producing a 42-state model:
//! index 0..6 Cartesian, index `6 + row*6 + col` STM element `(row, col)` (row-major). This
//! test integrates that 42-state with the existing Dopri5 over `GetDerivatives` and checks it
//! against GMAT's own 42-state propagation on the same golden arc (fixture generated by GMAT's
//! Python API: `docs/teamlog/adr-002-amendment-draft-stm.md` records the exact commands).
use gmat_sys::integrate::Dopri5;
use gmat_sys::Gmat;
use serde::Deserialize;
use std::path::PathBuf;
use std::time::Instant;

#[derive(Deserialize)]
struct StmFixture {
    duration_s: f64,
    initial_state_42: Vec<f64>,
    final_state_42: Vec<f64>,
    det_phi_t1: f64,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/stm_golden.json")
}

/// Row-major index of STM element (row, col) inside the 42-state vector, matching GMAT's own
/// layout (verified against `Spacecraft::GetRmatrixParameter("STM")` element-by-element in the
/// Python ground truth this fixture was generated from).
fn stm_idx(row: usize, col: usize) -> usize {
    6 + row * 6 + col
}

fn det6(m: &[f64]) -> f64 {
    // 3x3 cofactor expansion generalised to 6x6 via a straightforward Gaussian elimination
    // (this is a sanity check, not a hot path).
    let mut a = [[0.0f64; 6]; 6];
    for r in 0..6 {
        for c in 0..6 {
            a[r][c] = m[r * 6 + c];
        }
    }
    let mut det = 1.0;
    for i in 0..6 {
        let mut pivot = i;
        for r in (i + 1)..6 {
            if a[r][i].abs() > a[pivot][i].abs() {
                pivot = r;
            }
        }
        if a[pivot][i] == 0.0 {
            return 0.0;
        }
        if pivot != i {
            a.swap(pivot, i);
            det = -det;
        }
        det *= a[i][i];
        for r in (i + 1)..6 {
            let f = a[r][i] / a[i][i];
            let (pivot_row, rows_below) = a.split_at_mut(r);
            let (dst, src) = (&mut rows_below[0], &pivot_row[i]);
            for c in i..6 {
                dst[c] -= f * src[c];
            }
        }
    }
    det
}

#[test]
fn rust_driven_42state_stm_matches_gmat_and_is_internally_consistent() {
    let _engine = gmat_sys::engine_lock();
    let fixture: StmFixture = serde_json::from_str(&std::fs::read_to_string(fixture_path()).unwrap()).unwrap();

    let gmat = Gmat::setup(&Gmat::default_startup_file()).expect("GMAT setup");

    let build_sat = |name: &str| {
        let sat = gmat.construct("Spacecraft", name).unwrap();
        sat.set_str("DateFormat", "UTCGregorian").unwrap();
        sat.set_str("Epoch", "01 Jan 2026 00:00:00.000").unwrap();
        sat.set_str("CoordinateSystem", "EarthMJ2000Eq").unwrap();
        sat.set_str("DisplayStateType", "Keplerian").unwrap();
        for (k, v) in [
            ("SMA", 6878.0),
            ("ECC", 0.001),
            ("INC", 51.6),
            ("RAAN", 30.0),
            ("AOP", 0.0),
            ("TA", 0.0),
            ("DryMass", 500.0),
            ("Cd", 2.2),
            ("Cr", 1.8),
            ("DragArea", 5.0),
            ("SRPArea", 5.0),
        ] {
            sat.set_real(k, v).unwrap();
        }
        sat
    };
    let build_fm = |name: &str| {
        let fm = gmat.construct("ForceModel", name).unwrap();
        fm.set_str("CentralBody", "Earth").unwrap();
        let grav = gmat.construct("GravityField", "").unwrap();
        grav.set_str("BodyName", "Earth").unwrap();
        grav.set_str("PotentialFile", "JGM2.cof").unwrap();
        grav.set_int("Degree", 8).unwrap();
        grav.set_int("Order", 8).unwrap();
        fm.add_force(&grav).unwrap();
        for body in ["Luna", "Sun"] {
            let pm = gmat.construct("PointMassForce", "").unwrap();
            pm.set_str("BodyName", body).unwrap();
            fm.add_force(&pm).unwrap();
        }
        fm
    };

    // --- Model A: 42-state (STM requested). ---
    let sat_stm = build_sat("StmSpikeSat");
    let fm_stm = build_fm("StmSpikeFM");
    gmat.initialize().unwrap();
    let model_stm = gmat.derivative_model_with_stm(&fm_stm, &sat_stm).expect("42-state derivative model");
    assert_eq!(model_stm.dimension(), 42, "PropagationStateManager::SetProperty(\"STM\", sc) did not grow the state to 42");

    let x0 = model_stm.state().unwrap();
    assert_eq!(x0.len(), 42);
    for (a, b) in x0.iter().zip(&fixture.initial_state_42) {
        assert!((a - b).abs() < 1e-9, "initial 42-state differs from GMAT's own: {x0:?} vs {:?}", fixture.initial_state_42);
    }
    // Phi(t0, t0) = I.
    for row in 0..6 {
        for col in 0..6 {
            let expect = if row == col { 1.0 } else { 0.0 };
            assert_eq!(x0[stm_idx(row, col)], expect, "Phi(t0,t0) not identity at ({row},{col})");
        }
    }

    // --- Model B: plain 6-state, same spacecraft/force model construction, for the
    // "requesting the STM must not change the 6-state derivatives" check. ---
    let sat_plain = build_sat("StmSpikePlainSat");
    let fm_plain = build_fm("StmSpikePlainFM");
    gmat.initialize().unwrap();
    let model_plain = gmat.derivative_model(&fm_plain, &sat_plain).expect("6-state derivative model");
    assert_eq!(model_plain.dimension(), 6);
    let x0_plain = model_plain.state().unwrap();

    let d0_stm = model_stm.derivatives(&x0, 0.0).unwrap();
    let d0_plain = model_plain.derivatives(&x0_plain, 0.0).unwrap();
    for i in 0..6 {
        assert!(
            (d0_stm[i] - d0_plain[i]).abs() < 1e-15,
            "6-state derivative changed when STM was requested: {} vs {} at index {i}",
            d0_stm[i], d0_plain[i]
        );
    }
    // Layout: d(pos)/dt == velocity, same as the plain 6-state golden test.
    for i in 0..3 {
        assert!((d0_stm[i] - x0[3 + i]).abs() < 1e-12);
    }
    // The STM derivative block must not be all zero at t0 (d(Phi)/dt = A(t) Phi is being
    // filled, not left at the PrepareDerivativeArray() zero-init).
    let stm_deriv_nonzero = (0..36).any(|k| d0_stm[6 + k].abs() > 1e-20);
    assert!(stm_deriv_nonzero, "STM derivative block is all zero: GetDerivatives is not filling d(Phi)/dt = A(t) Phi");

    // --- Integrate the 42-state with the kernel's own Dopri5, exactly as the plain golden
    // test does for the 6-state. ---
    let start = Instant::now();
    let (x1, stats) = Dopri5::default()
        .integrate(|t, x, out| model_stm.derivatives_into(x, t, out), &x0, 0.0, fixture.duration_s)
        .expect("integration");
    let elapsed = start.elapsed();
    eprintln!(
        "[gmat-sys STM spike] 42-state: {} steps, {} rejected, {} GetDerivatives calls in {:.3} s ({:.2} us/call)",
        stats.steps, stats.rejected, stats.evaluations,
        elapsed.as_secs_f64(), 1e6 * elapsed.as_secs_f64() / stats.evaluations as f64
    );

    // 6-state agreement vs GMAT's own 42-state run (position/velocity), same metric as the
    // plain golden test.
    let dr = (0..3).map(|i| (x1[i] - fixture.final_state_42[i]).powi(2)).sum::<f64>().sqrt() * 1e3;
    let dv = (3..6).map(|i| (x1[i] - fixture.final_state_42[i]).powi(2)).sum::<f64>().sqrt() * 1e3;
    eprintln!("[gmat-sys STM spike] position error vs GMAT: {dr:.4} m, velocity error: {dv:.3e} m/s");
    assert!(dr < 0.05, "42-state position error {dr} m exceeds the plain golden's tolerance (0.05 m)");
    assert!(dv < 5e-5, "42-state velocity error {dv} m/s exceeds the plain golden's tolerance (5e-5 m/s)");

    // STM agreement vs GMAT's own final STM.
    let mut max_abs_err = 0.0f64;
    let mut max_rel_err = 0.0f64;
    for row in 0..6 {
        for col in 0..6 {
            let ours = x1[stm_idx(row, col)];
            let theirs = fixture.final_state_42[stm_idx(row, col)];
            let abs_err = (ours - theirs).abs();
            max_abs_err = max_abs_err.max(abs_err);
            let scale = theirs.abs().max(1.0);
            max_rel_err = max_rel_err.max(abs_err / scale);
        }
    }
    eprintln!("[gmat-sys STM spike] STM max abs error vs GMAT: {max_abs_err:.6e}, max rel error (scale>=1): {max_rel_err:.6e}");
    // Measured empirically (see docs/teamlog/adr-002-amendment-draft-stm.md); the STM entries
    // reach ~1.8e5 in magnitude (position sensitivity to a full day of many-body dynamics), so
    // this is a loose absolute bound with the actual measurement recorded in the amendment
    // draft, not a tightened-until-it-passes tolerance.
    assert!(max_abs_err < 1.0, "STM max abs error {max_abs_err} exceeds 1.0 (see amendment draft for the measured value)");

    // Internal consistency: our own integrated Phi should still be near-symplectic
    // (det(Phi) ~ 1 for a conservative gravitational system), and close to GMAT's own
    // det(Phi) at t1 (fixture.det_phi_t1).
    let phi_flat: Vec<f64> = (0..36).map(|k| x1[6 + k]).collect();
    let det = det6(&phi_flat);
    eprintln!("[gmat-sys STM spike] det(Phi) at t1: ours = {det:.12}, GMAT's = {:.12}", fixture.det_phi_t1);
    assert!((det - 1.0).abs() < 1e-4, "det(Phi) at t1 = {det} is not near 1 (Liouville/symplecticity check)");
}
