"""F3b (docs/feasibility-plan.md's F3 milestone): the feasibility-study panel
(web/js/panels/feasibility_panel.js). Same "run the real code, don't port it" discipline
as tests/test_viewer_panels.py (this file's own sibling, deliberately NOT imported from --
this repo's existing viewer test files each stay self-contained, tests/test_viewer_panels.py's
own module docstring / this file's own duplication of its fixture-building code follows
that same convention): this file publishes the real, frozen
``tests/fixtures/demo_two_instance.runproducts.bin`` fixture through the real
``POST /api/cdm/run`` route so ``web/js/panels_check.mjs``'s OTHER (pre-existing) checks
have a real, valid scenario to run against without throwing (sections 1-9 of that script
assume a fully-formed scenario; this file's job is only section 10, the feasibility panel,
but the script is one file that runs top to bottom) -- then hands panels_check.mjs the
REAL, measured ``demo_two_instance_sweep`` study fixture
(``web/js/fixtures/feasibility_sweep_fixture.json``, generated by
``web/js/fixtures/gen_feasibility_sweep_fixture.py`` -- see that script's own module
docstring for exactly which numbers are measured vs. structural placeholders) as
``input.feasibilitySweep``, which panels_check.mjs's own "10. feasibility panel (F3b)"
section reads.
"""
from __future__ import annotations

import json
import math
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from altavista.pb.altavista.v1 import run_pb2
from altavista.server import create_app

REPO_ROOT = Path(__file__).resolve().parent.parent
PANELS_CHECK = REPO_ROOT / "web" / "js" / "panels_check.mjs"
FROZEN_DEMO_RUN_BUNDLE_PATH = REPO_ROOT / "tests" / "fixtures" / "demo_two_instance.runproducts.bin"
FEASIBILITY_SWEEP_FIXTURE_PATH = REPO_ROOT / "web" / "js" / "fixtures" / "feasibility_sweep_fixture.json"

NODE = shutil.which("node")


def _require_node() -> str:
    if NODE is None:
        pytest.skip("node is not installed in this environment; web/js/panels_check.mjs "
                     "drives real ES modules and is intentionally not ported to Python.")
    return NODE


# --------------------------------------------------------------------------- fixtures
# The next four fixtures duplicate tests/test_viewer_panels.py's own fixtures of the same
# name/shape (not imported -- see this module's own docstring on why) purely so
# panels_check.mjs's PRE-EXISTING sections (1-9) have a real, well-formed `scenario` to
# run against without throwing; this file's own assertions below never look at their
# results (see `_failed`/the test functions' own substring filters, which only ever
# match `'feasibility '`-prefixed check names -- this file's section 10 addition, never
# touching sections 1-9's own already-covered territory).
@pytest.fixture(scope="module")
def frozen_demo_bundle_bytes() -> bytes:
    return FROZEN_DEMO_RUN_BUNDLE_PATH.read_bytes()


@pytest.fixture(scope="module")
def run_products(frozen_demo_bundle_bytes: bytes) -> run_pb2.RunProducts:
    rp = run_pb2.RunProducts()
    rp.ParseFromString(frozen_demo_bundle_bytes)
    return rp


@pytest.fixture(scope="module")
def published_frozen_demo_scenario(frozen_demo_bundle_bytes: bytes) -> dict:
    with tempfile.TemporaryDirectory() as d:
        app = create_app(texture_dir=Path(d), web_dir=Path(d))
        client = TestClient(app)
        resp = client.post("/api/cdm/run", content=frozen_demo_bundle_bytes,
                            headers={"content-type": "application/x-protobuf"})
        assert resp.status_code == 200, resp.text
        name = resp.json()["name"]
        resp = client.get(f"/api/scenario/{name}")
        assert resp.status_code == 200, resp.text
        return resp.json()


def _quat_conjugate_rotate(qx, qy, qz, qw, vx, vy, vz):
    """See tests/test_viewer_panels.py's own identical helper for the full derivation
    comment -- duplicated verbatim here rather than imported (this module's own
    docstring)."""
    ux, uy, uz = -qx, -qy, -qz
    c1x = uy * vz - uz * vy
    c1y = uz * vx - ux * vz
    c1z = ux * vy - uy * vx
    c2x = uy * c1z - uz * c1y
    c2y = uz * c1x - ux * c1z
    c2z = ux * c1y - uy * c1x
    return (vx + 2 * qw * c1x + 2 * c2x,
            vy + 2 * qw * c1y + 2 * c2y,
            vz + 2 * qw * c1z + 2 * c2z)


WGS84_A_M = 6378137.0
WGS84_B_M = 6356752.314245
WGS84_E2 = 1 - (WGS84_B_M ** 2) / (WGS84_A_M ** 2)


def _ecef_to_geodetic_iterative(x_m, y_m, z_m):
    p = math.hypot(x_m, y_m)
    lon = math.atan2(y_m, x_m)
    lat = math.atan2(z_m, p * (1 - WGS84_E2))
    for _ in range(10):
        sin_lat = math.sin(lat)
        n = WGS84_A_M / math.sqrt(1 - WGS84_E2 * sin_lat * sin_lat)
        h = p / math.cos(lat) - n
        lat = math.atan2(z_m, p * (1 - WGS84_E2 * n / (n + h)))
    sin_lat = math.sin(lat)
    n = WGS84_A_M / math.sqrt(1 - WGS84_E2 * sin_lat * sin_lat)
    h = p / math.cos(lat) - n
    return math.degrees(lon), math.degrees(lat), h


@pytest.fixture(scope="module")
def feasibility_sweep() -> dict:
    """The real, measured ``demo_two_instance_sweep`` study, as ``scenario.sweep``'s own
    wire shape -- read directly from the committed JSON fixture (no GMAT/venv needed to
    run this test; see web/js/fixtures/gen_feasibility_sweep_fixture.py's own module
    docstring for provenance)."""
    fixture = json.loads(FEASIBILITY_SWEEP_FIXTURE_PATH.read_text())
    sweep = fixture["scenario"]["sweep"]
    assert sweep["sweepId"] == "demo_two_instance_sweep"
    return sweep


@pytest.fixture(scope="module")
def panels_check_input_path(tmp_path_factory, published_frozen_demo_scenario, run_products, feasibility_sweep):
    """Builds the one JSON file web/js/panels_check.mjs reads -- the real published
    scenario (so sections 1-9 do not throw on a missing field, see this module's own
    docstring), the two hand-computed values sections 3/5 need, and this file's own
    addition: `feasibilitySweep`, the real measured study fixture."""
    scenario = dict(published_frozen_demo_scenario)
    scenario["scores"] = {}

    flt = next(s for s in scenario["spacecraft"] if s["name"] == "demo_flt")
    earth = next(b for b in scenario["bodies"] if b["name"] == "Earth")
    assert earth["t"][0] == flt["t"][0], "test assumption: Earth and demo_flt share their first sample epoch"
    qx, qy, qz, qw = earth["quat"][0:4]
    ex, ey, ez = earth["pos"][0:3]
    sx, sy, sz = flt["pos"][0:3]
    rel_km = (sx - ex, sy - ey, sz - ez)
    body_fixed_km = _quat_conjugate_rotate(qx, qy, qz, qw, *rel_km)
    lon_deg, lat_deg, alt_m = _ecef_to_geodetic_iterative(*(c * 1000 for c in body_fixed_km))

    t0, t1 = scenario["t0"], scenario["t1"]
    fault = next(e for e in scenario["events"] if e["type"] == "fault")
    expected_fault_pct = (fault["t"] - t0) / (t1 - t0) * 100

    payload = {
        "scenario": scenario,
        "expectedGroundTrack": {"lonDeg": lon_deg, "latDeg": lat_deg, "altM": alt_m},
        "expectedFaultTimelinePercent": expected_fault_pct,
        "feasibilitySweep": feasibility_sweep,
    }
    d = tmp_path_factory.mktemp("feasibility_panels_check")
    path = d / "panels_input.json"
    path.write_text(json.dumps(payload))
    return path


@pytest.fixture(scope="module")
def panels_data(panels_check_input_path) -> dict:
    node = _require_node()
    proc = subprocess.run([node, str(PANELS_CHECK), str(panels_check_input_path)],
                           cwd=str(PANELS_CHECK.parent), capture_output=True, text=True, timeout=30)
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        raise AssertionError(f"panels_check.mjs did not print valid JSON (exit {proc.returncode})\n"
                              f"stdout: {proc.stdout!r}\nstderr: {proc.stderr}")
    return data


def _failed(data: dict, substring: str) -> list[str]:
    return [c["name"] for c in data["checks"] if substring in c["name"] and not c["pass"]]


def _matched(data: dict, substring: str) -> list[dict]:
    matches = [c for c in data["checks"] if substring in c["name"]]
    assert matches, f"no checks matched substring {substring!r} -- panels_check.mjs's check names changed?"
    return matches


# ============================================================== scoreNames / gridAxes
def test_score_names_real_fixture_and_empty_sweep(panels_data):
    """Fails against a `scoreNames` that fabricates/omits a score name from the real
    fixture's own two measures, or one that throws instead of returning `[]` for a
    null/absent sweep."""
    failed = _failed(panels_data, "feasibility scoreNames:")
    assert not failed, f"scoreNames checks failed: {failed}"


def test_grid_axes_real_fixture_and_arity(panels_data):
    """Fails against a `gridAxes`/`axisLevels` that get the real fixture's 2 axis keys
    or their measured levels (5.0/25.0, 10.0/30.0) wrong, or that assume a second axis
    exists for a 1-axis study (the documented 1-axis grid case) or cap out below 3 axes
    (the documented flat-list-fallback trigger)."""
    failed = _failed(panels_data, "feasibility gridAxes:")
    assert not failed, f"gridAxes checks failed: {failed}"
    failed2 = _failed(panels_data, "feasibility axisLevels:")
    assert not failed2, f"axisLevels checks failed: {failed2}"
    failed3 = _failed(panels_data, "feasibility 1-axis grid:")
    assert not failed3, f"1-axis grid arity checks failed: {failed3}"
    failed4 = _failed(panels_data, "feasibility 3-axis grid:")
    assert not failed4, f"3-axis grid arity checks failed: {failed4}"


# =================================================================== gridRows: real data
def test_grid_rows_real_fixture_matches_hand_arithmetic(panels_data):
    """The load-bearing check for this panel's colour data: the real fixture's own
    aggregate mean/stdDev (population, /n) at point 0 must match hand arithmetic over the
    manager's own measured per-draw values, `passFraction` must be `null` (never coerced
    to 0/false -- this study declares no Objective), rows must be pointIndex-ascending,
    and the point with the smallest/largest mean must get t=0/t=1 exactly."""
    failed = _failed(panels_data, "feasibility gridRows: real fixture")
    assert not failed, f"gridRows real-fixture checks failed: {failed}"


# ============================================ gridRows: zero-width range (break-and-restore #1)
def test_grid_rows_zero_width_colour_range_is_never_nan_or_zero(panels_data):
    """The brief's own required decision, verified: when every point's mean for the
    chosen score is identical (a zero-width [min, max] range), every point's `t` is
    exactly 0.5 (the scale's neutral midpoint), never `NaN` (a naive `0/0`) and never
    silently `0` (which would misrepresent a flat study as having a real minimum).
    Break-and-restore evidence for this exact check is in web/js/REPORT_F3b.md."""
    failed = _failed(panels_data, "ZERO-WIDTH RANGE")
    assert not failed, f"zero-width colour range checks failed: {failed}"


# ======================================== gridRows: no aggregate for a point (documented decision)
def test_grid_rows_point_with_no_aggregate_is_distinguishable_from_t_zero(panels_data):
    """Fails against a `gridRows` that coalesces "no aggregate at all for this (point,
    score)" (e.g. every draw at that point failed) into `t=0` -- the brief's own explicit
    requirement that this case "must be distinguishable from t=0, not silently coloured
    as the minimum". `heatBucket(null)` must report its own `'none'` sentinel, never a
    numeric bucket a real value could also produce."""
    failed = _failed(panels_data, "NO-AGGREGATE POINT")
    assert not failed, f"no-aggregate-point checks failed: {failed}"


# ===================================================================== heatBucket
def test_heat_bucket_boundaries(panels_data):
    """Hand-derivable boundary cases for `heatBucket`'s own documented formula
    (`floor(clamp(t,0,1) * buckets)`, clamped to `buckets - 1`): fails against an
    off-by-one at either end, or an implementation that does not clamp `t=0.999` down
    into the top bucket."""
    failed = _failed(panels_data, "feasibility heatBucket:")
    assert not failed, f"heatBucket boundary checks failed: {failed}"


# ============================================================= drawRows: real data
def test_draw_rows_real_fixture_values_and_identifiers(panels_data):
    """The per-point distribution across draws must show the REAL per-draw values (not
    the aggregate mean), ascending by drawIndex, with runId/configHash/productsUri
    carried through unchanged, and must degrade to `[]` (never a throw) for an absent
    point or a null sweep."""
    failed = _failed(panels_data, "feasibility drawRows: real fixture")
    assert not failed, f"drawRows real-fixture checks failed: {failed}"


# ============================================ drawRows: failed sample (break-and-restore #2)
def test_draw_rows_failed_sample_is_never_dropped(panels_data):
    """The brief's own required rule, verified: a point with one succeeded and one
    failed draw reports BOTH as rows (never filters the failed one out), the failed row
    carries its real error text and `value=null` (never a fabricated 0), is never
    openable, and the succeeded row in the same point is unaffected.
    `isSampleOpenable` independently agrees. Break-and-restore evidence for this exact
    check is in web/js/REPORT_F3b.md."""
    failed = _failed(panels_data, "FAILED-SAMPLE-NOT-DROPPED")
    assert not failed, f"failed-sample-not-dropped checks failed: {failed}"


# ==================================================== defaultScoreName (F5.1, question 197)
def test_default_score_name_prefers_a_varying_score_over_alphabetical_first(panels_data):
    """The round's own brief claimed the real fixture's first score is constant -- it is
    NOT (both `demo_flt_rmag_at_end` and `demo_mvr_rmag_at_end` vary across the grid,
    verified directly against the fixture); the real-fixture check here only PINS that
    fact, it cannot by itself distinguish the new "first varying score" rule from the
    old `names[0]` rule. The actual discriminating check is VARYING-OVER-ALPHABETICAL: a
    hand-built sweep where the first sorted score is constant and a later one varies --
    fails against the old `names.includes(selectedScore) ? selectedScore : (names[0] ||
    null)` rule, which would return the constant score. The remaining checks cover this
    task's own required edge cases: every score constant (or a single-point grid) falls
    back to the first sorted name rather than null; a score with fewer than two
    aggregate points cannot be shown to vary and is skipped; a null/malformed sweep
    returns null, never throws.
    """
    failed = _failed(panels_data, "feasibility defaultScoreName")
    assert not failed, f"defaultScoreName checks failed: {failed}"


# ------------------------------------------------------------------------------ overall
def test_feasibility_checks_report(panels_data, capsys):
    """Prints every check this file's fixture drove (not only the `feasibility `-prefixed
    ones -- the full table, so a `pytest -q -s` run of this file alone shows whether
    sections 1-9 happened to also fail, which would mean this file's own scenario
    plumbing is broken, not the feasibility panel itself)."""
    with capsys.disabled():
        print(f"\npanels_check.mjs (feasibility): {len(panels_data['checks'])} checks total")
        feasibility_checks = _matched(panels_data, "feasibility ")
        n_fail = sum(1 for c in feasibility_checks if not c["pass"])
        print(f"  {len(feasibility_checks)} feasibility-panel checks, {n_fail} failing")
        for c in feasibility_checks:
            mark = "PASS" if c["pass"] else "FAIL"
            print(f"  [{mark}] {c['name']}")
    failed = [c["name"] for c in feasibility_checks if not c["pass"]]
    assert not failed, f"feasibility-panel checks failed: {failed}"
