"""Committed Python protobuf bindings for proto/altavista/v1.

Generated by altavista/pb/generate.py -- do not hand-edit the *_pb2.py files.
See generate.py's module docstring for why the ``altavista/v1`` nesting is kept and
why the generated modules' cross-imports are rewritten to relative (M26.1).
"""
from __future__ import annotations

from .altavista.v1 import (
    command_pb2,
    core_pb2,
    dynamics_service_pb2,
    edge_pb2,
    entity_pb2,
    envelope_pb2,
    lockstep_pb2,
    packet_pb2,
    run_pb2,
    system_pb2,
    trajectory_pb2,
)

# The gRPC stub needs the optional ``grpcio`` extra (``pip install -e ".[grpc]"``); the
# messages above do not. Importing the package must not require grpcio (question 85), so
# the stub is exposed as ``None`` when grpcio is absent and callers that need it check.
try:
    from .altavista.v1 import dynamics_service_pb2_grpc
except ImportError:  # grpcio not installed
    dynamics_service_pb2_grpc = None  # type: ignore[assignment]

try:
    from .altavista.v1 import lockstep_pb2_grpc
except ImportError:  # grpcio not installed
    lockstep_pb2_grpc = None  # type: ignore[assignment]

__all__ = [
    "command_pb2",
    "core_pb2",
    "dynamics_service_pb2",
    "edge_pb2",
    "entity_pb2",
    "envelope_pb2",
    "lockstep_pb2",
    "packet_pb2",
    "run_pb2",
    "system_pb2",
    "trajectory_pb2",
    "dynamics_service_pb2_grpc",
    "lockstep_pb2_grpc",
]
