//! The second plugin's own pinned acceptance test (question 200(a)): CSV -> `AdsbCsvSource`
//! -> `BatchBuilder::build_batches_for_config` with a fixed test key -> chain, exactly the
//! same path `tests/plugin_replay.rs` exercises for the first plugin -- see that file's own
//! module doc for the "pure/no-wire half" framing this file repeats for the second source.
//!
//! Fixture: `tests/fixtures/adsb/sample.csv`, committed, synthetic, hand-generated by an
//! analytic formula (no network, no live receiver, no recorded feed -- question 154). See
//! `tests/fixtures/adsb/README.md` for exactly how each row's values were produced and
//! every pinned number below.

use av_edge::hash;
use av_edge::pb;
use av_edge::plugin::adsb::{AdsbCsvSource, FRAME_ID};
use av_edge::plugin::{BatchBuilder, BatchingRule, MeasurementSource, Pacing, PluginConfig};
use av_edge::sign;

const TEST_KEY_PEM: &[u8] = include_bytes!("fixtures/test_signing_key.pem");
const TEST_PUB_PEM: &[u8] = include_bytes!("fixtures/test_signing_key.pub.pem");

/// The one row `tests/fixtures/adsb/README.md` documents as REFUSED: an out-of-range
/// latitude, deliberately placed as the fixture's own last line so it can be dropped by a
/// plain "all lines but the last" slice ([`valid_fixture_csv_bytes`]) rather than a second,
/// parallel fixture file -- one committed CSV serves both this file's pinned-success test
/// and its refusal test.
const BAD_ROW: &str = "a00001,1700000075,95.5000,-117.7750,10075.0";

/// The full committed fixture, bytes exactly as checked in -- including [`BAD_ROW`] as its
/// last line. Used directly by the refusal test below; `AdsbCsvSource::from_csv` aborts at
/// the first bad row it hits (no silent skip), so this is never fed to
/// [`build_source_and_batches`].
fn fixture_csv_bytes() -> Vec<u8> {
    std::fs::read(std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/adsb/sample.csv")).expect("reading tests/fixtures/adsb/sample.csv")
}

/// [`fixture_csv_bytes`] with its trailing [`BAD_ROW`] line dropped -- the 45 rows every
/// pinned count in this file (measurement count, batch count, chain head, config hash) is
/// computed from. Asserts the dropped line really is [`BAD_ROW`] before dropping it, so a
/// future edit to the fixture that moves or removes that row fails loudly here rather than
/// silently changing what "valid" means.
fn valid_fixture_csv_bytes() -> Vec<u8> {
    let full = String::from_utf8(fixture_csv_bytes()).expect("fixture is valid UTF-8");
    let mut lines: Vec<&str> = full.lines().collect();
    let last = lines.pop().expect("fixture has at least one data line after the header");
    assert_eq!(last, BAD_ROW, "the fixture's trailing line must be exactly the documented bad row -- see tests/fixtures/adsb/README.md");
    let mut out = lines.join("\n");
    out.push('\n');
    out.into_bytes()
}

/// A trivial, empty-fields `PacketCodec` -- `AdsbCsvSource` never reads it (`crate::plugin::
/// adsb`'s own module doc: `PluginConfig.codec_bytes` is a `PortTrafficSource`-specific
/// knob), but `PluginConfig::validate` still requires `codec_bytes` to decode as a real
/// `pb::PacketCodec`, so this is the harmless placeholder every test in this file shares.
fn placeholder_codec_bytes() -> Vec<u8> {
    PluginConfig::encode_codec(&pb::PacketCodec {
        id: "unused-adsb-placeholder".to_string(),
        apid: 0,
        is_command: false,
        secondary_header_bytes: 0,
        user_data_bytes: 0,
        description: "AdsbCsvSource does not read a PacketCodec".to_string(),
        fields: vec![],
    })
}

/// ADS-B 1090ES is an unencrypted public broadcast (`crate::plugin::adsb`'s own module
/// doc's "Label and clearance" section) -- `"UNCLASSIFIED"`, one of `core.proto`'s own
/// three worked examples for `Label.marking`, not the first plugin's `"CUI"`.
fn label_bytes() -> Vec<u8> {
    PluginConfig::encode_label(&pb::Label { marking: "UNCLASSIFIED".to_string(), caveats: vec![] })
}

/// Isotropic `(25 m)^2` per ECEF axis -- declared, not derived from the fixture's own
/// exact analytic rows; see `crate::plugin::adsb`'s own module doc's "Noise" section for
/// where the number comes from.
const NOISE_R: [f64; 9] = [625.0, 0.0, 0.0, 0.0, 625.0, 0.0, 0.0, 0.0, 625.0];

fn config() -> PluginConfig {
    PluginConfig {
        producer_id: "demo-adsb-replay-plugin".to_string(),
        plugin_version: "0.1.0".to_string(),
        instance: "adsb".to_string(),
        port: "csv_replay".to_string(),
        direction: pb::PortDirection::Out as i32,
        codec_bytes: placeholder_codec_bytes(),
        component_fields: vec!["x".to_string(), "y".to_string(), "z".to_string()],
        frame_id: FRAME_ID.to_string(),
        sensor_id: "adsb-receiver".to_string(),
        measurement_id: "adsb_position".to_string(),
        shard_key: "adsb-demo".to_string(),
        noise_r: NOISE_R.to_vec(),
        label_bytes: label_bytes(),
        clearance: "UNCLASSIFIED".to_string(),
        leaf_fingerprint_sha256: String::new(),
        batching: BatchingRule::PerEpoch,
        pacing: Pacing::AsFastAsPossible,
    }
}

fn signing_key() -> openssl::ec::EcKey<openssl::pkey::Private> {
    sign::load_signing_key(TEST_KEY_PEM).unwrap()
}
fn verify_key() -> openssl::ec::EcKey<openssl::pkey::Public> {
    av_edge::verify::load_verifying_key(TEST_PUB_PEM).unwrap()
}

fn build_source_and_batches() -> (AdsbCsvSource, Vec<pb::MeasurementBatch>) {
    let cfg = config();
    let source = AdsbCsvSource::from_csv(&valid_fixture_csv_bytes(), &cfg).expect("the fixture's 45 valid rows parse");
    let builder = BatchBuilder::new(cfg.batching).unwrap();
    let provenance = cfg.batch_provenance("run-adsb-demo-1", 1_700_000_000_000_000_000);
    let key = signing_key();
    let batches = builder.build_batches_for_config(&source, &cfg, &provenance, &key).expect("batches build and sign");
    (source, batches)
}

// -----------------------------------------------------------------------------------------
// Pinned numbers -- this file's own acceptance list, mirroring tests/plugin_replay.rs's own
// "the batch count and the chain head pinned" convention.
// -----------------------------------------------------------------------------------------

/// `tests/fixtures/adsb/sample.csv` carries 45 valid rows (3 aircraft x 15 epochs each,
/// one refused row not counted) over 15 distinct TAI epochs, all three aircraft sharing
/// every epoch -- `BatchingRule::PerEpoch` therefore produces exactly one batch per epoch.
/// See `tests/fixtures/adsb/README.md`'s own row-by-row accounting.
const EXPECTED_MEASUREMENT_COUNT: usize = 45;
const EXPECTED_BATCH_COUNT: usize = 15;

/// `BatchBuilder::build_batches`'s own final `batch_hash` for the full 15-batch chain
/// built from [`config`] against the committed fixture and `tests/fixtures/
/// test_signing_key.pem` -- computed once (`batch_count_and_chain_head_are_pinned` below
/// prints it) and pinned here, hex, lowercase.
const EXPECTED_CHAIN_HEAD_HEX: &str = "8f6bd8ce345cf4155b60f0126727c2e0ff2c4a8c8c198c3545d9eafa58158668";

/// `PluginConfig::config_hash()` for [`config`] -- pinned the same way.
const EXPECTED_CONFIG_HASH_HEX: &str = "a550bf530c860876ed51f371221b0092770ab01572b07a8819ec01d2e26977d5";

#[test]
fn matching_measurement_and_epoch_counts() {
    let (source, _batches) = build_source_and_batches();
    let total_measurements: usize = source.groups().iter().map(|(_, ms)| ms.len()).sum();
    assert_eq!(source.groups().len(), EXPECTED_BATCH_COUNT, "one group per distinct epoch");
    assert_eq!(total_measurements, EXPECTED_MEASUREMENT_COUNT, "45 valid rows, one refused row excluded");
    for (_, measurements) in source.groups() {
        assert_eq!(measurements.len(), 3, "all three aircraft share every valid epoch in this fixture");
    }
}

#[test]
fn batch_count_and_chain_head_and_config_hash_are_pinned() {
    let (_source, batches) = build_source_and_batches();
    assert_eq!(batches.len(), EXPECTED_BATCH_COUNT);

    let head_hex = hash::hex_encode(&batches.last().unwrap().batch_hash);
    let config_hash_hex = hash::hex_encode(&config().config_hash());
    println!("adsb measurement count: {EXPECTED_MEASUREMENT_COUNT}");
    println!("adsb batch count: {}", batches.len());
    println!("adsb chain head (batch_hash of the last batch), hex: {head_hex}");
    println!("adsb PluginConfig::config_hash(), hex: {config_hash_hex}");

    assert_eq!(head_hex, EXPECTED_CHAIN_HEAD_HEX, "the adsb replay's own chain head must be pinned, not merely printed");
    assert_eq!(config_hash_hex, EXPECTED_CONFIG_HASH_HEX, "the adsb replay's own config_hash must be pinned, not merely printed");
}

#[test]
fn walk_chain_verifies_the_whole_emitted_chain() {
    let (_source, batches) = build_source_and_batches();
    let vk = verify_key();
    let result = av_edge::chain::walk_chain("demo-adsb-replay-plugin", &batches, &vk);
    assert!(result.ok, "{result:?}");
    assert_eq!(result.checked, EXPECTED_BATCH_COUNT as u64);
}

/// Every batch carries the label/clearance `PluginConfig` declares (question 200(a)'s
/// "Label and clearance" requirement, same path as the first plugin).
#[test]
fn every_batch_carries_the_declared_label_and_clearance() {
    let cfg = config();
    let (_source, batches) = build_source_and_batches();
    let expected_label = cfg.label().unwrap();
    for batch in &batches {
        assert_eq!(batch.label.as_ref().unwrap(), &expected_label);
        assert_eq!(batch.shard_key, cfg.shard_key);
    }
    let manifest = cfg.manifest().unwrap();
    assert_eq!(manifest.clearance, "UNCLASSIFIED");
}

/// Every emitted measurement carries `entity_hint` = the row's own `icao24`, and `frame_id`
/// = [`FRAME_ID`] -- the two facts `crates/av-kernel/tests/edge_plugin_adsb_ecef_crosscheck.rs`
/// and `crates/av-cdm/tests/adsb_frame_resolution.rs` depend on.
#[test]
fn measurements_carry_their_icao24_as_entity_hint_and_the_declared_frame_id() {
    let (source, _batches) = build_source_and_batches();
    let mut seen_icaos = std::collections::BTreeSet::new();
    for (_, measurements) in source.groups() {
        for m in measurements {
            assert_eq!(m.frame_id, FRAME_ID);
            assert_eq!(m.z.len(), 3, "ECEF Cartesian position");
            assert!(!m.entity_hint.is_empty(), "entity_hint must carry the row's icao24");
            seen_icaos.insert(m.entity_hint.clone());
        }
    }
    assert_eq!(seen_icaos, ["a00001", "a00002", "a00003"].into_iter().map(String::from).collect());
}

/// The one fixture row that must be refused (`tests/fixtures/adsb/README.md`'s own pinned
/// row): line 47, `icao24=a00001`, `lat_deg=95.5` -- out of the valid `[-90, 90]` range.
/// Fed here as the real committed fixture's own bytes (`fixture_csv_bytes`, unmodified),
/// not a synthetic in-test string -- `AdsbCsvSource::from_csv` walks all 45 valid rows
/// first (proving it does not stop early) and only then hits [`BAD_ROW`] and refuses.
#[test]
fn the_fixtures_one_bad_row_is_a_typed_refusal_not_a_silent_skip() {
    let full = fixture_csv_bytes();
    let full_text = String::from_utf8(full).expect("fixture is valid UTF-8");
    assert!(full_text.trim_end().ends_with(BAD_ROW), "the bad row must be the fixture's last line, per the README");

    let err = AdsbCsvSource::from_csv(full_text.as_bytes(), &config()).unwrap_err();
    assert!(matches!(err, av_edge::plugin::PluginError::AdsbLatitudeOutOfRange { line: 47, lat_deg } if lat_deg == 95.5), "{err:?}");

    // The same refusal, reachable through the exact bad row text alone (a synthetic
    // string, for isolation): confirms the refusal is about this row's content, not an
    // artifact of everything preceding it in the full file.
    let isolated = format!("icao24,utc_unix_s,lat_deg,lon_deg,geo_alt_m\n{BAD_ROW}\n");
    let err = AdsbCsvSource::from_csv(isolated.as_bytes(), &config()).unwrap_err();
    assert!(matches!(err, av_edge::plugin::PluginError::AdsbLatitudeOutOfRange { line: 2, lat_deg } if lat_deg == 95.5), "{err:?}");
}

/// Two runs over the identical committed CSV must produce the identical chain head --
/// canonical body bytes and `batch_hash` are a deterministic function of content (`av_edge`'s
/// own crate module doc); only the ECDSA signature bytes differ run to run.
#[test]
fn two_runs_over_the_same_csv_produce_the_identical_chain_head() {
    let (_source_a, batches_a) = build_source_and_batches();
    let (_source_b, batches_b) = build_source_and_batches();
    assert_eq!(batches_a.len(), batches_b.len());
    let head_a = hash::hex_encode(&batches_a.last().unwrap().batch_hash);
    let head_b = hash::hex_encode(&batches_b.last().unwrap().batch_hash);
    assert_eq!(head_a, head_b, "the chain head must be identical across two independent replays of the same CSV");
    for (a, b) in batches_a.iter().zip(batches_b.iter()) {
        assert_eq!(hash::canonical_body_bytes(a), hash::canonical_body_bytes(b));
        assert_eq!(a.batch_hash, b.batch_hash);
    }
    let any_signature_differs = batches_a.iter().zip(batches_b.iter()).any(|(a, b)| a.signature != b.signature);
    assert!(any_signature_differs, "ECDSA nonces are random -- expected at least one signature to differ");
}
