//! `Tai`: nanoseconds on the TAI scale, and the boundary conversions to/from UTC, TT, GPS
//! and GMAT's A.1 (ADR-001 "Time").
//!
//! Every `epoch_ns` / `tai_ns` field in `altavista.v1` is TAI (`int64` nanoseconds); UTC,
//! TT, GPS and A.1 exist only at a boundary (ingest, egress, the GMAT adapter). TAI has no
//! discontinuities -- the versioned leap-second table is needed only when a scale that
//! *does* (UTC) is involved.
//!
//! ## `Tai`'s origin
//!
//! `Tai(0)` shares the Unix epoch's calendar label (`1970-01-01T00:00:00`) but is *not*
//! simultaneous with UTC nanosecond `0`: this crate defines
//! `tai_ns := utc_ns_proleptic + offset_in_force(t) * 1_000_000_000`, exactly the relation
//! `data/time/leap_seconds.json` records (`tai_effective_ns = utc_effective_unix_ns +
//! tai_utc_offset_seconds * 1e9`), where `utc_ns_proleptic` is a naive calendar count (every
//! day is exactly 86 400 SI seconds -- it cannot represent a leap second's extra tick).
//! `Tai(0)` is therefore the TAI instant ten seconds after `1970-01-01T00:00:00 UTC`
//! (the table's pre-1972 clamp value; see below), not TAI's own historical epoch. This is
//! the same convention most "TAI nanoseconds since Unix epoch" clocks use, and it keeps
//! every conversion here pure integer/table arithmetic instead of also carrying the
//! sub-second pre-1972 TAI-UTC drift.
//!
//! ## Documented approximations (read before trusting a value outside 1972-2017)
//!
//! - **Before 1972-01-01T00:00:00Z**: `data/time/leap_seconds.json` has no entries (the
//!   whole-second leap-second era starts there). Both directions clamp to the table's first
//!   entry (`offset = 10 s`), the same convention SPICE's own `deltet_` routine uses and the
//!   JSON documents as `clamped_before_first_entry`. The real pre-1972 relationship (the
//!   "rubber second", `DELTET/DELTA_T_A, K, EB, M`) is **not** modeled. Do not trust this
//!   crate's UTC conversions before 1972.
//! - **After the table's last entry (2017-01-01T00:00:00Z, `offset = 37 s`)**: both
//!   directions extrapolate that offset forward. This is correct only until IERS schedules
//!   another leap second and the table is regenerated (`scripts/gen_leap_seconds.py`) --
//!   there is no way for a static table to know about a leap second that has not been
//!   announced yet.
//! - **The UTC->TAI direction has no unique inverse across a positive leap second.** A
//!   proleptic UTC nanosecond count cannot represent the leap second itself (there is no
//!   `23:59:60`), so the last SI second before a leap-second insertion and the leap second
//!   itself collapse onto the *same* `utc_ns` value under this encoding. Concretely: for a
//!   step from `old_offset` to `old_offset + 1` at `utc_effective_unix_ns`, both
//!   `Tai(tai_effective_ns - 1_000_000_000)` (the leap second) and
//!   `Tai(tai_effective_ns)` (the following instant) map to `to_utc_nanos() ==
//!   utc_effective_unix_ns`. [`Tai::from_utc_nanos`] resolves the collision by always
//!   choosing the *post*-insertion reading (the new offset applies at and after the
//!   boundary, inclusive) -- documented and tested at
//!   [`tests::from_utc_nanos_resolves_the_leap_second_collision_to_the_post_insertion_reading`].
//!   A caller that specifically needs the pre-insertion instant must subtract one second
//!   from `utc_ns` before calling `from_utc_nanos`; there is no way to ask for it directly,
//!   because the leap second has no `utc_ns` value of its own.
//!
//! No silent wrong answers: every rule above is deliberate, tested at the boundary, and
//! restated in `README.md`.

use std::sync::OnceLock;

use serde::Deserialize;

/// The versioned leap-second table shipped with this crate, generated by
/// `scripts/gen_leap_seconds.py` from GMAT's SPICE leap-second kernel
/// (`GMAT R2026a/data/time/SPICELeapSecondKernel.tls`). Embedded at compile time so the
/// crate has no runtime dependency on the repository layout.
const LEAP_SECONDS_JSON: &str = include_str!("../../../data/time/leap_seconds.json");

#[derive(Debug, Deserialize)]
struct LeapSecondsDoc {
    entries: Vec<LeapSecondEntry>,
}

#[derive(Debug, Deserialize, Clone, Copy)]
struct LeapSecondEntry {
    tai_utc_offset_seconds: i64,
    utc_effective_unix_ns: i64,
    tai_effective_ns: i64,
}

static TABLE: OnceLock<LeapSecondsDoc> = OnceLock::new();

fn table() -> &'static [LeapSecondEntry] {
    &TABLE
        .get_or_init(|| {
            let doc: LeapSecondsDoc = serde_json::from_str(LEAP_SECONDS_JSON).expect(
                "data/time/leap_seconds.json is malformed; it is embedded at compile time and \
                 regenerated by scripts/gen_leap_seconds.py, so this can only mean the file was \
                 hand-edited into an invalid shape",
            );
            assert!(
                !doc.entries.is_empty(),
                "data/time/leap_seconds.json has no entries"
            );
            doc
        })
        .entries
}

/// Nanoseconds on the TAI scale (ADR-001 "Time"). See the module docs for `Tai`'s origin
/// and the documented UTC-boundary approximations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Tai(i64);

/// `TT = TAI + 32.184 s` exactly (IAU definition; constant, no leap-second table involved).
const TT_MINUS_TAI_NS: i64 = 32_184_000_000;
/// `GPS = TAI - 19 s` exactly. GPS time has not tracked leap seconds since its 1980-01-06
/// epoch, so this offset is a fixed constant, not table-driven.
const GPS_MINUS_TAI_NS: i64 = 19_000_000_000;
/// `A1 = TAI + 0.034 381 7 s` exactly (GMAT's A.1 atomic time, ADR-001).
const A1_MINUS_TAI_NS: i64 = 34_381_700;
/// GMAT's "Modified Julian Date" of the Unix epoch: `JD(1970-01-01T00:00:00) = 2440587.5`
/// (a standard constant) and GMAT's `MJD = JD - 2430000.0` (documented in
/// `altavista/timeutil.py` as `GMAT_MJD_JD_OFFSET`), so `GMAT_MJD(unix epoch) = 10587.5`.
const GMAT_MJD_AT_UNIX_EPOCH: f64 = 10_587.5;
const NS_PER_DAY: f64 = 86_400_000_000_000.0;
/// `GMAT_MJD_AT_UNIX_EPOCH * NS_PER_DAY` computed once as an exact `i64`
/// (`10_587.5 * 86_400_000_000_000 = 914_760_000_000_000_000`, well inside `i64`'s
/// exact-integer range) -- used by [`Tai::from_a1_mjd_parts`], which recombines in `i128` (see
/// that function's own doc) and so can use this single large constant directly. NOT used by
/// [`Tai::to_a1_mjd_parts`], which never forms a quantity this large at all -- see that
/// function's own doc, "Totality", and the day/ns-of-day split constants below.
const GMAT_MJD_AT_UNIX_EPOCH_A1_NS: i64 = 914_760_000_000_000_000;
/// `NS_PER_DAY` as an exact `i64`, for the integer-only day/fraction split in
/// [`Tai::to_a1_mjd_parts`] / [`Tai::from_a1_mjd_parts`].
const NS_PER_DAY_I64: i64 = 86_400_000_000_000;
/// `GMAT_MJD_AT_UNIX_EPOCH_A1_NS`'s OWN day/ns-of-day split: `10_587` whole days
/// (`GMAT_MJD_AT_UNIX_EPOCH.floor()`) plus a half day (`43_200_000_000_000` ns) -- pinned by
/// [`tests::gmat_mjd_at_unix_epoch_a1_ns_day_ns_split_is_exact`]. [`Tai::to_a1_mjd_parts`]
/// adds this SMALL pair to its own small `(d0, r0)` split instead of ever forming the full
/// ~9.15e17-magnitude `GMAT_MJD_AT_UNIX_EPOCH_A1_NS` sum -- see that function's own doc.
const GMAT_MJD_AT_UNIX_EPOCH_A1_WHOLE_DAYS: i64 = 10_587;
const GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY: i64 = 43_200_000_000_000;

impl Tai {
    pub const fn from_nanos(ns: i64) -> Self {
        Self(ns)
    }

    pub const fn as_nanos(self) -> i64 {
        self.0
    }

    /// This instant on the TT (Terrestrial Time) scale, nanoseconds since the same origin.
    pub const fn to_tt_nanos(self) -> i64 {
        self.0 + TT_MINUS_TAI_NS
    }

    /// The TAI instant simultaneous with `tt_ns` on the TT scale.
    pub const fn from_tt_nanos(tt_ns: i64) -> Self {
        Self(tt_ns - TT_MINUS_TAI_NS)
    }

    /// This instant on the GPS time scale, nanoseconds since the same origin.
    pub const fn to_gps_nanos(self) -> i64 {
        self.0 - GPS_MINUS_TAI_NS
    }

    /// The TAI instant simultaneous with `gps_ns` on the GPS scale.
    pub const fn from_gps_nanos(gps_ns: i64) -> Self {
        Self(gps_ns + GPS_MINUS_TAI_NS)
    }

    /// This instant as a GMAT A.1 Modified Julian Date (`A1MJD = JD - 2430000.0`, a float
    /// of days). GMAT-boundary only (ADR-001): nothing outside the GMAT adapter should
    /// carry an `f64` epoch.
    pub fn to_a1_mjd(self) -> f64 {
        let a1_ns = self.0 + A1_MINUS_TAI_NS;
        GMAT_MJD_AT_UNIX_EPOCH + (a1_ns as f64) / NS_PER_DAY
    }

    /// The TAI instant simultaneous with `a1_mjd` on GMAT's A.1 scale.
    pub fn from_a1_mjd(a1_mjd: f64) -> Self {
        let a1_ns = ((a1_mjd - GMAT_MJD_AT_UNIX_EPOCH) * NS_PER_DAY).round() as i64;
        Self(a1_ns - A1_MINUS_TAI_NS)
    }

    /// This instant as GMAT's A.1 Modified Julian Date, split EXACTLY into an integer
    /// whole-day count and an integer nanosecond-of-day offset: `(whole_days, ns_of_day)`,
    /// with `ns_of_day` always in `[0, 86_400_000_000_000)` -- a full day of nanoseconds --
    /// even when `whole_days` is negative. Added BESIDE [`Tai::to_a1_mjd`] (question 226,
    /// closing question 225's finding that `to_a1_mjd`'s single-`f64` ULP is ~600 ns at
    /// today's magnitude), never replacing it: [`Tai::to_a1_mjd`] is used by
    /// `av-kernel`'s `drm::executor`, `drm::binding` and several tests, and is unchanged.
    ///
    /// # Shape chosen: integer nanosecond-of-day, not an `f64` fraction
    ///
    /// The charter allows either "integer days plus fraction, or integer nanoseconds". This
    /// function returns integer days plus an INTEGER nanosecond-of-day fraction (not an
    /// `f64` fraction), because the round trip this API exists for
    /// (`from_a1_mjd_parts(t.to_a1_mjd_parts()) == t`, see `mod tests`) must be BIT-EXACT --
    /// zero nanoseconds of residual -- and only integer arithmetic is exact by construction.
    /// An `f64` fraction-of-day, however small in magnitude, is still a binary
    /// floating-point value: `86_400_000_000_000` is not a power of two, so most
    /// nanosecond-of-day counts have no exact `f64` representation as a fraction of a day,
    /// and a fraction built that way would reintroduce a (much smaller, but nonzero)
    /// rounding step. A bare "total A.1 nanoseconds since MJD 0" `i64` (no day/fraction
    /// split at all) was also considered and is exact too, but it is not "parts" -- it does
    /// not hand a caller (this crate's own `av-orbital::tdb::tai_ns_to_tdb_jd2`, whose
    /// two-part Julian Date wants exactly a whole-day integer plus a small remainder) the
    /// whole-day integer directly, without a further division. So: integer days, integer
    /// nanosecond-of-day.
    ///
    /// # Totality: this function is total over every `i64`, and never panics
    ///
    /// `av-cdm` is shared with every track, and this function is reachable from a DRM-supplied
    /// epoch (`av_orbital::tdb::tai_ns_to_tdb_jd2` is on the derivative path); a DRM's start
    /// epoch is a plain `i64` nanosecond field, so `i64::MAX`/`i64::MIN` are inputs a DRM can
    /// supply, and `av-orbital`'s own rule is "typed throughout -- no panic on any input a DRM
    /// could supply". `to_a1_mjd` (unchanged) never panics; this function does not either.
    ///
    /// An earlier revision of this function formed the sum `self.0 + A1_MINUS_TAI_NS +
    /// GMAT_MJD_AT_UNIX_EPOCH_A1_NS` (~9.15e17 in magnitude) directly and panicked outside a
    /// derived ~year-2233 bound. That sum is never necessary: `GMAT_MJD_AT_UNIX_EPOCH_A1_NS`
    /// is itself exactly `GMAT_MJD_AT_UNIX_EPOCH_A1_WHOLE_DAYS` (`10_587`) whole days plus
    /// `GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY` (`43_200_000_000_000`, half a day) of nanoseconds
    /// (pinned by [`tests::gmat_mjd_at_unix_epoch_a1_ns_day_ns_split_is_exact`]), so this
    /// function splits `self.0` FIRST and adds that small, fixed pair to its own small split,
    /// never forming the large sum at all:
    ///
    /// - `d0 = self.0.div_euclid(NS_PER_DAY_I64)`, `r0 = self.0.rem_euclid(NS_PER_DAY_I64)` --
    ///   `r0` is exactly in `[0, NS_PER_DAY_I64)`, and `|d0| <= i64::MAX / NS_PER_DAY_I64 ~=
    ///   1.07e5`, far below any `i64` overflow risk for what follows;
    /// - `r_total = r0 + (GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY + A1_MINUS_TAI_NS)`: the added
    ///   constant is small and fixed (`~4.32e13`), so `r_total` is always in
    ///   `[0, 2 * NS_PER_DAY_I64)` -- AT MOST ONE carry is ever needed, computed directly (no
    ///   loop);
    /// - `whole_days = d0 + GMAT_MJD_AT_UNIX_EPOCH_A1_WHOLE_DAYS + carry` -- `d0`'s own bound
    ///   above means this addition of small numbers cannot overflow for ANY `i64` input.
    ///
    /// No step here can overflow for any `self.0`, so this function returns for every `i64`
    /// TAI-nanosecond value -- see
    /// [`tests::to_a1_mjd_parts_and_from_a1_mjd_parts_are_total_over_i64_extremes`].
    ///
    /// # Negative epochs: floor division, not truncation
    ///
    /// `i64`'s `/` and `%` truncate toward zero, which gives a NEGATIVE remainder for a
    /// negative dividend (e.g. `-1_i64 / 86_400_000_000_000 == 0` and
    /// `-1_i64 % 86_400_000_000_000 == -1`) -- wrong for a `[0, day)` nanosecond-of-day
    /// fraction. This function uses [`i64::div_euclid`] / [`i64::rem_euclid`] (floor
    /// division) instead, so `ns_of_day` is always non-negative and `whole_days` is the
    /// floor of the true (possibly negative) day count.
    pub fn to_a1_mjd_parts(self) -> (i64, i64) {
        let d0 = self.0.div_euclid(NS_PER_DAY_I64);
        let r0 = self.0.rem_euclid(NS_PER_DAY_I64); // exactly in [0, NS_PER_DAY_I64)

        let extra_ns = GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY + A1_MINUS_TAI_NS;
        let r_total = r0 + extra_ns; // in [extra_ns, NS_PER_DAY_I64 + extra_ns) subset [0, 2*NS_PER_DAY_I64)
        let (ns_of_day, carry) = if r_total >= NS_PER_DAY_I64 { (r_total - NS_PER_DAY_I64, 1) } else { (r_total, 0) };

        let whole_days = d0 + GMAT_MJD_AT_UNIX_EPOCH_A1_WHOLE_DAYS + carry;
        (whole_days, ns_of_day)
    }

    /// The inverse of [`Tai::to_a1_mjd_parts`]: the TAI instant for an A.1 `(whole_days,
    /// ns_of_day)` pair. `ns_of_day` must be in `[0, 86_400_000_000_000)`, exactly the
    /// range [`Tai::to_a1_mjd_parts`] always returns; checked with a plain `assert!` (not
    /// `debug_assert!`) because a caller passing an out-of-range value would otherwise get a
    /// silently wrong epoch instead of a clear failure. Added BESIDE [`Tai::from_a1_mjd`],
    /// never replacing it.
    ///
    /// # No real range gap versus [`Tai::to_a1_mjd_parts`]
    ///
    /// Recombining `whole_days` and `ns_of_day` into "nanoseconds since MJD 0" can reach
    /// ~1.01e19 in magnitude at `Tai`'s own `i64` extremes (`MJD 0` is ~9.15e17 ns, ~10,587.5
    /// days, EARLIER than `Tai`'s own origin, so shifting the whole `i64` TAI-nanosecond range
    /// to be MJD-0-relative overflows `i64`, which tops out at ~9.22e18) -- that is why an
    /// earlier revision of this function, which formed that combined `i64` directly via
    /// `checked_mul`/`checked_add`, could not round-trip `to_a1_mjd_parts`'s own output at the
    /// extremes and had to panic there. Rather than accept that as a genuine limitation, this
    /// revision combines in `i128` (a native Rust primitive, not a new dependency; `i128`
    /// trivially holds ~1.01e19) and only narrows to `i64` at the very end, where the RESULT
    /// (not the intermediate) is guaranteed to fit for any `(whole_days, ns_of_day)` that
    /// actually came from `to_a1_mjd_parts` of a real `Tai` -- proven by
    /// [`tests::to_a1_mjd_parts_and_from_a1_mjd_parts_are_total_over_i64_extremes`], which
    /// round-trips `i64::MAX`, `i64::MIN`, `i64::MAX - 1` and `i64::MIN + 1` exactly. There is
    /// therefore NO asymmetry between the two functions for any real epoch. The final
    /// `i64::try_from` (and the `ns_of_day` range assert above) remain as a defensive,
    /// programming-error check -- defensible on a value only THIS crate's own code
    /// constructs, unlike a panic on a DRM-supplied epoch -- for a `(whole_days, ns_of_day)`
    /// pair that could not have come from any `Tai` at all (e.g. a `whole_days` many orders of
    /// magnitude outside anything `to_a1_mjd_parts` could ever produce).
    pub fn from_a1_mjd_parts(whole_days: i64, ns_of_day: i64) -> Self {
        assert!(
            (0..NS_PER_DAY_I64).contains(&ns_of_day),
            "Tai::from_a1_mjd_parts: ns_of_day {ns_of_day} out of [0, {NS_PER_DAY_I64})"
        );
        let mjd0_ns: i128 = (whole_days as i128) * (NS_PER_DAY_I64 as i128) + (ns_of_day as i128);
        let offset: i128 = (GMAT_MJD_AT_UNIX_EPOCH_A1_NS as i128) + (A1_MINUS_TAI_NS as i128);
        let tai_ns_128 = mjd0_ns - offset;
        let tai_ns = i64::try_from(tai_ns_128).unwrap_or_else(|_| {
            panic!(
                "Tai::from_a1_mjd_parts: (whole_days={whole_days}, ns_of_day={ns_of_day}) does \
                 not correspond to any representable Tai (i64 nanoseconds) -- this pair could \
                 not have come from Tai::to_a1_mjd_parts of a real Tai value"
            )
        });
        Self(tai_ns)
    }

    /// This instant's UTC nanosecond count (proleptic: every day is 86 400 SI seconds).
    ///
    /// Table-driven and total, but **not** injective across a positive leap second -- see
    /// the module docs. Clamps to the table's first offset before 1972 and extrapolates its
    /// last offset after the table's final entry.
    pub fn to_utc_nanos(self) -> i64 {
        let entries = table();
        let offset = entries
            .iter()
            .rev()
            .find(|e| e.tai_effective_ns <= self.0)
            .unwrap_or(&entries[0])
            .tai_utc_offset_seconds;
        self.0 - offset * 1_000_000_000
    }

    /// The TAI instant for a UTC nanosecond count (proleptic: every day is 86 400 SI
    /// seconds).
    ///
    /// Table-driven and total. At a leap-second boundary this resolves the UTC->TAI
    /// ambiguity by choosing the offset newly in force at (and after) `utc_ns` -- see the
    /// module docs.
    pub fn from_utc_nanos(utc_ns: i64) -> Self {
        let entries = table();
        let offset = entries
            .iter()
            .rev()
            .find(|e| e.utc_effective_unix_ns <= utc_ns)
            .unwrap_or(&entries[0])
            .tai_utc_offset_seconds;
        Self(utc_ns + offset * 1_000_000_000)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entries() -> &'static [LeapSecondEntry] {
        table()
    }

    #[test]
    fn table_has_the_expected_span() {
        let e = entries();
        assert_eq!(e.len(), 28);
        assert_eq!(e[0].tai_utc_offset_seconds, 10);
        assert_eq!(e.last().unwrap().tai_utc_offset_seconds, 37);
    }

    #[test]
    fn to_utc_nanos_is_exact_at_every_boundary() {
        for e in entries() {
            assert_eq!(
                Tai::from_nanos(e.tai_effective_ns).to_utc_nanos(),
                e.utc_effective_unix_ns,
                "boundary at offset {}",
                e.tai_utc_offset_seconds
            );
        }
    }

    #[test]
    fn to_utc_nanos_just_before_and_just_after_every_boundary() {
        // Skip the first entry: "just before" it is the pre-1972 clamp, covered separately.
        for e in entries().iter().skip(1) {
            let old_offset = entries()
                .iter()
                .rev()
                .find(|p| p.tai_effective_ns < e.tai_effective_ns)
                .unwrap()
                .tai_utc_offset_seconds;

            // One ns before the boundary: still the old offset.
            let before = Tai::from_nanos(e.tai_effective_ns - 1).to_utc_nanos();
            assert_eq!(before, e.tai_effective_ns - 1 - old_offset * 1_000_000_000);

            // Exactly at, and one ns after, the boundary: the new offset.
            let at = Tai::from_nanos(e.tai_effective_ns).to_utc_nanos();
            assert_eq!(at, e.utc_effective_unix_ns);
            let after = Tai::from_nanos(e.tai_effective_ns + 1).to_utc_nanos();
            assert_eq!(after, e.utc_effective_unix_ns + 1);
        }
    }

    #[test]
    fn from_utc_nanos_just_before_and_at_every_boundary() {
        for e in entries().iter().skip(1) {
            let old_offset = entries()
                .iter()
                .rev()
                .find(|p| p.utc_effective_unix_ns < e.utc_effective_unix_ns)
                .unwrap()
                .tai_utc_offset_seconds;

            // One ns before the boundary: still the old offset.
            let before = Tai::from_utc_nanos(e.utc_effective_unix_ns - 1);
            assert_eq!(
                before.as_nanos(),
                e.utc_effective_unix_ns - 1 + old_offset * 1_000_000_000
            );

            // Exactly at the boundary: the new offset (the documented "post-insertion" rule).
            let at = Tai::from_utc_nanos(e.utc_effective_unix_ns);
            assert_eq!(at.as_nanos(), e.tai_effective_ns);
        }
    }

    #[test]
    fn from_utc_nanos_resolves_the_leap_second_collision_to_the_post_insertion_reading() {
        // The documented ambiguity: the leap second itself and the instant one second later
        // both round-trip to the same utc_ns. from_utc_nanos always recovers the *later* one.
        for e in entries().iter().skip(1) {
            let leap_second_tai = Tai::from_nanos(e.tai_effective_ns - 1_000_000_000);
            let post_insertion_tai = Tai::from_nanos(e.tai_effective_ns);
            assert_eq!(leap_second_tai.to_utc_nanos(), post_insertion_tai.to_utc_nanos());

            let recovered = Tai::from_utc_nanos(leap_second_tai.to_utc_nanos());
            assert_eq!(recovered, post_insertion_tai);
            assert_ne!(
                recovered, leap_second_tai,
                "the leap second itself is unrecoverable from its utc_ns by design"
            );
        }
    }

    #[test]
    fn pre_1972_clamps_to_the_first_offset() {
        let first = entries()[0];
        // Well before the first entry, on both scales.
        let tai = Tai::from_nanos(first.tai_effective_ns - 10 * 365 * 86_400_000_000_000);
        assert_eq!(
            tai.to_utc_nanos(),
            tai.as_nanos() - first.tai_utc_offset_seconds * 1_000_000_000
        );

        let utc_ns = first.utc_effective_unix_ns - 10 * 365 * 86_400_000_000_000;
        let recovered = Tai::from_utc_nanos(utc_ns);
        assert_eq!(
            recovered.as_nanos(),
            utc_ns + first.tai_utc_offset_seconds * 1_000_000_000
        );
    }

    #[test]
    fn post_table_extrapolates_the_last_offset() {
        let last = entries().last().unwrap();
        let far_future_tai = Tai::from_nanos(last.tai_effective_ns + 20 * 365 * 86_400_000_000_000);
        assert_eq!(
            far_future_tai.to_utc_nanos(),
            far_future_tai.as_nanos() - last.tai_utc_offset_seconds * 1_000_000_000
        );
    }

    #[test]
    fn tt_round_trips_and_matches_the_iau_constant() {
        let t = Tai::from_nanos(1_700_000_000_123_456_789);
        assert_eq!(t.to_tt_nanos(), t.as_nanos() + 32_184_000_000);
        assert_eq!(Tai::from_tt_nanos(t.to_tt_nanos()), t);
    }

    #[test]
    fn gps_round_trips_and_matches_the_constant_offset() {
        let t = Tai::from_nanos(1_700_000_000_123_456_789);
        assert_eq!(t.to_gps_nanos(), t.as_nanos() - 19_000_000_000);
        assert_eq!(Tai::from_gps_nanos(t.to_gps_nanos()), t);
    }

    #[test]
    fn a1_mjd_of_the_tai_origin_matches_the_documented_constant() {
        // Tai(0) -> A1 ns = 34_381_700 -> days since the Unix epoch's MJD.
        let mjd = Tai::from_nanos(0).to_a1_mjd();
        let expected = 10_587.5 + 34_381_700.0 / 86_400_000_000_000.0;
        assert!((mjd - expected).abs() < 1e-15, "{mjd} vs {expected}");
    }

    #[test]
    fn a1_mjd_round_trips_within_a_microsecond() {
        // f64 days at present-day magnitudes carry roughly microsecond resolution (ADR-001
        // "Alternatives considered"); this is the realistic bar for a round trip through it.
        for ns in [
            0_i64,
            1_700_000_000_000_000_000,
            -1_700_000_000_000_000_000,
            63_072_010_000_000_000, // first leap-second boundary
        ] {
            let t = Tai::from_nanos(ns);
            let back = Tai::from_a1_mjd(t.to_a1_mjd());
            let residual_ns = (back.as_nanos() - t.as_nanos()).abs();
            assert!(residual_ns < 1_000, "residual {residual_ns} ns for {ns}");
        }
    }

    /// Epochs exercised by the `to_a1_mjd_parts` tests below: every leap-second boundary in
    /// the embedded table, a dense minute-by-minute sweep across one present-day day,
    /// epochs decades before and after the Unix epoch, and explicit negative epochs
    /// (including far pre-1970).
    fn a1_mjd_parts_sweep_epochs() -> Vec<i64> {
        let mut epochs: Vec<i64> = entries().iter().map(|e| e.tai_effective_ns).collect();

        // Dense sweep across one present-day day, one point per minute (1440 points). The
        // exact calendar alignment of this anchor doesn't matter -- only its magnitude
        // (present-day) and the density of the sweep do.
        let day_start_tai_ns = 1_789_776_000_000_000_000_i64;
        for minute in 0..1440_i64 {
            epochs.push(day_start_tai_ns + minute * 60_000_000_000);
        }

        // Decades before and after the Unix epoch.
        const YEAR_NS: i64 = 365 * 86_400_000_000_000;
        for years in [-60_i64, -30, -10, 10, 30, 60, 100] {
            epochs.push(years * YEAR_NS);
        }

        // Explicit negative epochs, including far pre-1970.
        epochs.push(-1);
        epochs.push(-1_700_000_000_000_000_000);
        epochs.push(-5_000_000_000_000_000_000);

        epochs
    }

    #[test]
    fn to_a1_mjd_parts_round_trips_bit_exactly() {
        for ns in a1_mjd_parts_sweep_epochs() {
            let t = Tai::from_nanos(ns);
            let (day, ns_of_day) = t.to_a1_mjd_parts();
            assert!(
                (0..NS_PER_DAY_I64).contains(&ns_of_day),
                "ns_of_day {ns_of_day} out of range for TAI ns {ns}"
            );
            let back = Tai::from_a1_mjd_parts(day, ns_of_day);
            assert_eq!(
                back.as_nanos(),
                ns,
                "round trip mismatch for TAI ns {ns}: day={day} ns_of_day={ns_of_day}"
            );
        }
    }

    /// The improvement is MEASURED, not assumed: for the same sweep of epochs, round-trip
    /// through the OLD single-`f64` `to_a1_mjd`/`from_a1_mjd` path and through the NEW
    /// `to_a1_mjd_parts`/`from_a1_mjd_parts` path, and compare the residuals directly. The
    /// old path must show a nonzero residual SOMEWHERE (otherwise there was nothing to fix);
    /// the new path must be exactly zero everywhere.
    #[test]
    fn to_a1_mjd_parts_beats_the_f64_round_trip() {
        let mut max_old_residual_ns: i64 = 0;
        let mut max_new_residual_ns: i64 = 0;
        for ns in a1_mjd_parts_sweep_epochs() {
            let t = Tai::from_nanos(ns);

            // Old path: single f64 A.1 MJD.
            let old_back = Tai::from_a1_mjd(t.to_a1_mjd());
            let old_residual = (old_back.as_nanos() - ns).abs();
            max_old_residual_ns = max_old_residual_ns.max(old_residual);

            // New path: exact integer (day, ns_of_day) parts.
            let (day, ns_of_day) = t.to_a1_mjd_parts();
            let new_back = Tai::from_a1_mjd_parts(day, ns_of_day);
            let new_residual = (new_back.as_nanos() - ns).abs();
            max_new_residual_ns = max_new_residual_ns.max(new_residual);
            assert_eq!(new_residual, 0, "new (parts) path must be exactly zero residual for {ns}");
        }
        println!(
            "n3-a1-mjd-parts-residual: max old (single f64) round-trip residual = \
             {max_old_residual_ns} ns, max new (parts) round-trip residual = \
             {max_new_residual_ns} ns, over {} epochs",
            a1_mjd_parts_sweep_epochs().len()
        );
        assert!(
            max_old_residual_ns > 0,
            "expected the OLD single-f64 path to show some nonzero residual across this \
             sweep -- otherwise there was nothing for to_a1_mjd_parts to fix"
        );
        assert_eq!(max_new_residual_ns, 0, "the NEW parts path must be exactly zero everywhere");
    }

    /// Consistency with [`Tai::to_a1_mjd`]: the two-part value, recombined in `f64` (`day as
    /// f64 + frac`), must equal `to_a1_mjd()` to CLOSE to that `f64`'s own ULP -- so the new
    /// API is provably the SAME epoch at higher resolution, not a different one. The two
    /// values are produced by genuinely different arithmetic (one division of the whole sum
    /// vs. an integer euclidean split then a division of just the remainder), so a single
    /// exact ULP is not achievable in general; this test MEASURES the actual worst-case
    /// agreement across the sweep (printed below) rather than asserting a number from theory,
    /// and bounds it at a small, fixed multiple of the local ULP that comfortably covers the
    /// measured worst case (`n3-a1-mjd-parts-agreement` in the test output; measured max was
    /// 6 ULPs, at a small-magnitude epoch where `to_a1_mjd`'s own ULP is itself tiny in
    /// absolute nanoseconds).
    #[test]
    fn to_a1_mjd_parts_recombines_to_a1_mjd_within_its_own_ulp() {
        let mut max_diff_days: f64 = 0.0;
        let mut max_diff_ulps: f64 = 0.0;
        let mut worst_ns: i64 = 0;
        for ns in a1_mjd_parts_sweep_epochs() {
            let t = Tai::from_nanos(ns);
            let single = t.to_a1_mjd();
            let (day, ns_of_day) = t.to_a1_mjd_parts();
            let recombined = day as f64 + (ns_of_day as f64) / NS_PER_DAY;
            let diff = (recombined - single).abs();
            let ulp = if single >= 0.0 {
                single.next_up() - single
            } else {
                single - single.next_down()
            };
            let diff_ulps = if ulp > 0.0 { diff / ulp } else { 0.0 };
            if diff_ulps > max_diff_ulps {
                worst_ns = ns;
            }
            max_diff_days = max_diff_days.max(diff);
            max_diff_ulps = max_diff_ulps.max(diff_ulps);
        }
        println!(
            "n3-a1-mjd-parts-agreement: max diff vs to_a1_mjd() = {max_diff_days:e} days \
             ({max_diff_ulps} ULPs, worst at TAI ns {worst_ns}), over {} epochs",
            a1_mjd_parts_sweep_epochs().len()
        );
        assert!(
            max_diff_ulps <= 16.0,
            "recombined value drifted {max_diff_ulps} ULPs from to_a1_mjd() (worst at TAI ns \
             {worst_ns}) -- more than the measured, comfortably-bounded worst case"
        );
    }

    /// Pins the day/ns-of-day decomposition [`Tai::to_a1_mjd_parts`]'s own doc ("Totality")
    /// relies on, rather than leaving it asserted only in a comment.
    #[test]
    fn gmat_mjd_at_unix_epoch_a1_ns_day_ns_split_is_exact() {
        assert_eq!(
            GMAT_MJD_AT_UNIX_EPOCH_A1_WHOLE_DAYS * NS_PER_DAY_I64 + GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY,
            GMAT_MJD_AT_UNIX_EPOCH_A1_NS
        );
        // And that half-day is exactly what GMAT_MJD_AT_UNIX_EPOCH's own fractional part says.
        assert_eq!(GMAT_MJD_AT_UNIX_EPOCH_A1_NS_OF_DAY, NS_PER_DAY_I64 / 2);
    }

    /// `to_a1_mjd_parts` must be TOTAL (this function's own doc, "Totality"): a DRM can supply
    /// any `i64` TAI-nanosecond epoch, including the extremes, and this must never panic.
    /// `from_a1_mjd_parts` must then round-trip every one of those outputs EXACTLY (this
    /// function's own doc, "No real range gap") -- proving there is no asymmetry between the
    /// two functions for any real `Tai` value, not just for "reasonable" epochs.
    #[test]
    fn to_a1_mjd_parts_and_from_a1_mjd_parts_are_total_over_i64_extremes() {
        for ns in [i64::MAX, i64::MIN, i64::MAX - 1, i64::MIN + 1] {
            let t = Tai::from_nanos(ns);
            let (whole_days, ns_of_day) = t.to_a1_mjd_parts(); // must not panic
            assert!(
                (0..NS_PER_DAY_I64).contains(&ns_of_day),
                "ns_of_day {ns_of_day} out of range for TAI ns {ns}"
            );
            let back = Tai::from_a1_mjd_parts(whole_days, ns_of_day); // must not panic, must round-trip
            assert_eq!(
                back.as_nanos(),
                ns,
                "round trip mismatch at extreme TAI ns {ns}: whole_days={whole_days} ns_of_day={ns_of_day}"
            );
        }
    }
}
