//! `Tai`: nanoseconds on the TAI scale, and the boundary conversions to/from UTC, TT, GPS
//! and GMAT's A.1 (ADR-001 "Time").
//!
//! Every `epoch_ns` / `tai_ns` field in `altavista.v1` is TAI (`int64` nanoseconds); UTC,
//! TT, GPS and A.1 exist only at a boundary (ingest, egress, the GMAT adapter). TAI has no
//! discontinuities -- the versioned leap-second table is needed only when a scale that
//! *does* (UTC) is involved.
//!
//! ## `Tai`'s origin
//!
//! `Tai(0)` shares the Unix epoch's calendar label (`1970-01-01T00:00:00`) but is *not*
//! simultaneous with UTC nanosecond `0`: this crate defines
//! `tai_ns := utc_ns_proleptic + offset_in_force(t) * 1_000_000_000`, exactly the relation
//! `data/time/leap_seconds.json` records (`tai_effective_ns = utc_effective_unix_ns +
//! tai_utc_offset_seconds * 1e9`), where `utc_ns_proleptic` is a naive calendar count (every
//! day is exactly 86 400 SI seconds -- it cannot represent a leap second's extra tick).
//! `Tai(0)` is therefore the TAI instant ten seconds after `1970-01-01T00:00:00 UTC`
//! (the table's pre-1972 clamp value; see below), not TAI's own historical epoch. This is
//! the same convention most "TAI nanoseconds since Unix epoch" clocks use, and it keeps
//! every conversion here pure integer/table arithmetic instead of also carrying the
//! sub-second pre-1972 TAI-UTC drift.
//!
//! ## Documented approximations (read before trusting a value outside 1972-2017)
//!
//! - **Before 1972-01-01T00:00:00Z**: `data/time/leap_seconds.json` has no entries (the
//!   whole-second leap-second era starts there). Both directions clamp to the table's first
//!   entry (`offset = 10 s`), the same convention SPICE's own `deltet_` routine uses and the
//!   JSON documents as `clamped_before_first_entry`. The real pre-1972 relationship (the
//!   "rubber second", `DELTET/DELTA_T_A, K, EB, M`) is **not** modeled. Do not trust this
//!   crate's UTC conversions before 1972.
//! - **After the table's last entry (2017-01-01T00:00:00Z, `offset = 37 s`)**: both
//!   directions extrapolate that offset forward. This is correct only until IERS schedules
//!   another leap second and the table is regenerated (`scripts/gen_leap_seconds.py`) --
//!   there is no way for a static table to know about a leap second that has not been
//!   announced yet.
//! - **The UTC->TAI direction has no unique inverse across a positive leap second.** A
//!   proleptic UTC nanosecond count cannot represent the leap second itself (there is no
//!   `23:59:60`), so the last SI second before a leap-second insertion and the leap second
//!   itself collapse onto the *same* `utc_ns` value under this encoding. Concretely: for a
//!   step from `old_offset` to `old_offset + 1` at `utc_effective_unix_ns`, both
//!   `Tai(tai_effective_ns - 1_000_000_000)` (the leap second) and
//!   `Tai(tai_effective_ns)` (the following instant) map to `to_utc_nanos() ==
//!   utc_effective_unix_ns`. [`Tai::from_utc_nanos`] resolves the collision by always
//!   choosing the *post*-insertion reading (the new offset applies at and after the
//!   boundary, inclusive) -- documented and tested at
//!   [`tests::from_utc_nanos_resolves_the_leap_second_collision_to_the_post_insertion_reading`].
//!   A caller that specifically needs the pre-insertion instant must subtract one second
//!   from `utc_ns` before calling `from_utc_nanos`; there is no way to ask for it directly,
//!   because the leap second has no `utc_ns` value of its own.
//!
//! No silent wrong answers: every rule above is deliberate, tested at the boundary, and
//! restated in `README.md`.

use std::sync::OnceLock;

use serde::Deserialize;

/// The versioned leap-second table shipped with this crate, generated by
/// `scripts/gen_leap_seconds.py` from GMAT's SPICE leap-second kernel
/// (`GMAT R2026a/data/time/SPICELeapSecondKernel.tls`). Embedded at compile time so the
/// crate has no runtime dependency on the repository layout.
const LEAP_SECONDS_JSON: &str = include_str!("../../../data/time/leap_seconds.json");

#[derive(Debug, Deserialize)]
struct LeapSecondsDoc {
    entries: Vec<LeapSecondEntry>,
}

#[derive(Debug, Deserialize, Clone, Copy)]
struct LeapSecondEntry {
    tai_utc_offset_seconds: i64,
    utc_effective_unix_ns: i64,
    tai_effective_ns: i64,
}

static TABLE: OnceLock<LeapSecondsDoc> = OnceLock::new();

fn table() -> &'static [LeapSecondEntry] {
    &TABLE
        .get_or_init(|| {
            let doc: LeapSecondsDoc = serde_json::from_str(LEAP_SECONDS_JSON).expect(
                "data/time/leap_seconds.json is malformed; it is embedded at compile time and \
                 regenerated by scripts/gen_leap_seconds.py, so this can only mean the file was \
                 hand-edited into an invalid shape",
            );
            assert!(
                !doc.entries.is_empty(),
                "data/time/leap_seconds.json has no entries"
            );
            doc
        })
        .entries
}

/// Nanoseconds on the TAI scale (ADR-001 "Time"). See the module docs for `Tai`'s origin
/// and the documented UTC-boundary approximations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Tai(i64);

/// `TT = TAI + 32.184 s` exactly (IAU definition; constant, no leap-second table involved).
const TT_MINUS_TAI_NS: i64 = 32_184_000_000;
/// `GPS = TAI - 19 s` exactly. GPS time has not tracked leap seconds since its 1980-01-06
/// epoch, so this offset is a fixed constant, not table-driven.
const GPS_MINUS_TAI_NS: i64 = 19_000_000_000;
/// `A1 = TAI + 0.034 381 7 s` exactly (GMAT's A.1 atomic time, ADR-001).
const A1_MINUS_TAI_NS: i64 = 34_381_700;
/// GMAT's "Modified Julian Date" of the Unix epoch: `JD(1970-01-01T00:00:00) = 2440587.5`
/// (a standard constant) and GMAT's `MJD = JD - 2430000.0` (documented in
/// `altavista/timeutil.py` as `GMAT_MJD_JD_OFFSET`), so `GMAT_MJD(unix epoch) = 10587.5`.
const GMAT_MJD_AT_UNIX_EPOCH: f64 = 10_587.5;
const NS_PER_DAY: f64 = 86_400_000_000_000.0;

impl Tai {
    pub const fn from_nanos(ns: i64) -> Self {
        Self(ns)
    }

    pub const fn as_nanos(self) -> i64 {
        self.0
    }

    /// This instant on the TT (Terrestrial Time) scale, nanoseconds since the same origin.
    pub const fn to_tt_nanos(self) -> i64 {
        self.0 + TT_MINUS_TAI_NS
    }

    /// The TAI instant simultaneous with `tt_ns` on the TT scale.
    pub const fn from_tt_nanos(tt_ns: i64) -> Self {
        Self(tt_ns - TT_MINUS_TAI_NS)
    }

    /// This instant on the GPS time scale, nanoseconds since the same origin.
    pub const fn to_gps_nanos(self) -> i64 {
        self.0 - GPS_MINUS_TAI_NS
    }

    /// The TAI instant simultaneous with `gps_ns` on the GPS scale.
    pub const fn from_gps_nanos(gps_ns: i64) -> Self {
        Self(gps_ns + GPS_MINUS_TAI_NS)
    }

    /// This instant as a GMAT A.1 Modified Julian Date (`A1MJD = JD - 2430000.0`, a float
    /// of days). GMAT-boundary only (ADR-001): nothing outside the GMAT adapter should
    /// carry an `f64` epoch.
    pub fn to_a1_mjd(self) -> f64 {
        let a1_ns = self.0 + A1_MINUS_TAI_NS;
        GMAT_MJD_AT_UNIX_EPOCH + (a1_ns as f64) / NS_PER_DAY
    }

    /// The TAI instant simultaneous with `a1_mjd` on GMAT's A.1 scale.
    pub fn from_a1_mjd(a1_mjd: f64) -> Self {
        let a1_ns = ((a1_mjd - GMAT_MJD_AT_UNIX_EPOCH) * NS_PER_DAY).round() as i64;
        Self(a1_ns - A1_MINUS_TAI_NS)
    }

    /// This instant's UTC nanosecond count (proleptic: every day is 86 400 SI seconds).
    ///
    /// Table-driven and total, but **not** injective across a positive leap second -- see
    /// the module docs. Clamps to the table's first offset before 1972 and extrapolates its
    /// last offset after the table's final entry.
    pub fn to_utc_nanos(self) -> i64 {
        let entries = table();
        let offset = entries
            .iter()
            .rev()
            .find(|e| e.tai_effective_ns <= self.0)
            .unwrap_or(&entries[0])
            .tai_utc_offset_seconds;
        self.0 - offset * 1_000_000_000
    }

    /// The TAI instant for a UTC nanosecond count (proleptic: every day is 86 400 SI
    /// seconds).
    ///
    /// Table-driven and total. At a leap-second boundary this resolves the UTC->TAI
    /// ambiguity by choosing the offset newly in force at (and after) `utc_ns` -- see the
    /// module docs.
    pub fn from_utc_nanos(utc_ns: i64) -> Self {
        let entries = table();
        let offset = entries
            .iter()
            .rev()
            .find(|e| e.utc_effective_unix_ns <= utc_ns)
            .unwrap_or(&entries[0])
            .tai_utc_offset_seconds;
        Self(utc_ns + offset * 1_000_000_000)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entries() -> &'static [LeapSecondEntry] {
        table()
    }

    #[test]
    fn table_has_the_expected_span() {
        let e = entries();
        assert_eq!(e.len(), 28);
        assert_eq!(e[0].tai_utc_offset_seconds, 10);
        assert_eq!(e.last().unwrap().tai_utc_offset_seconds, 37);
    }

    #[test]
    fn to_utc_nanos_is_exact_at_every_boundary() {
        for e in entries() {
            assert_eq!(
                Tai::from_nanos(e.tai_effective_ns).to_utc_nanos(),
                e.utc_effective_unix_ns,
                "boundary at offset {}",
                e.tai_utc_offset_seconds
            );
        }
    }

    #[test]
    fn to_utc_nanos_just_before_and_just_after_every_boundary() {
        // Skip the first entry: "just before" it is the pre-1972 clamp, covered separately.
        for e in entries().iter().skip(1) {
            let old_offset = entries()
                .iter()
                .rev()
                .find(|p| p.tai_effective_ns < e.tai_effective_ns)
                .unwrap()
                .tai_utc_offset_seconds;

            // One ns before the boundary: still the old offset.
            let before = Tai::from_nanos(e.tai_effective_ns - 1).to_utc_nanos();
            assert_eq!(before, e.tai_effective_ns - 1 - old_offset * 1_000_000_000);

            // Exactly at, and one ns after, the boundary: the new offset.
            let at = Tai::from_nanos(e.tai_effective_ns).to_utc_nanos();
            assert_eq!(at, e.utc_effective_unix_ns);
            let after = Tai::from_nanos(e.tai_effective_ns + 1).to_utc_nanos();
            assert_eq!(after, e.utc_effective_unix_ns + 1);
        }
    }

    #[test]
    fn from_utc_nanos_just_before_and_at_every_boundary() {
        for e in entries().iter().skip(1) {
            let old_offset = entries()
                .iter()
                .rev()
                .find(|p| p.utc_effective_unix_ns < e.utc_effective_unix_ns)
                .unwrap()
                .tai_utc_offset_seconds;

            // One ns before the boundary: still the old offset.
            let before = Tai::from_utc_nanos(e.utc_effective_unix_ns - 1);
            assert_eq!(
                before.as_nanos(),
                e.utc_effective_unix_ns - 1 + old_offset * 1_000_000_000
            );

            // Exactly at the boundary: the new offset (the documented "post-insertion" rule).
            let at = Tai::from_utc_nanos(e.utc_effective_unix_ns);
            assert_eq!(at.as_nanos(), e.tai_effective_ns);
        }
    }

    #[test]
    fn from_utc_nanos_resolves_the_leap_second_collision_to_the_post_insertion_reading() {
        // The documented ambiguity: the leap second itself and the instant one second later
        // both round-trip to the same utc_ns. from_utc_nanos always recovers the *later* one.
        for e in entries().iter().skip(1) {
            let leap_second_tai = Tai::from_nanos(e.tai_effective_ns - 1_000_000_000);
            let post_insertion_tai = Tai::from_nanos(e.tai_effective_ns);
            assert_eq!(leap_second_tai.to_utc_nanos(), post_insertion_tai.to_utc_nanos());

            let recovered = Tai::from_utc_nanos(leap_second_tai.to_utc_nanos());
            assert_eq!(recovered, post_insertion_tai);
            assert_ne!(
                recovered, leap_second_tai,
                "the leap second itself is unrecoverable from its utc_ns by design"
            );
        }
    }

    #[test]
    fn pre_1972_clamps_to_the_first_offset() {
        let first = entries()[0];
        // Well before the first entry, on both scales.
        let tai = Tai::from_nanos(first.tai_effective_ns - 10 * 365 * 86_400_000_000_000);
        assert_eq!(
            tai.to_utc_nanos(),
            tai.as_nanos() - first.tai_utc_offset_seconds * 1_000_000_000
        );

        let utc_ns = first.utc_effective_unix_ns - 10 * 365 * 86_400_000_000_000;
        let recovered = Tai::from_utc_nanos(utc_ns);
        assert_eq!(
            recovered.as_nanos(),
            utc_ns + first.tai_utc_offset_seconds * 1_000_000_000
        );
    }

    #[test]
    fn post_table_extrapolates_the_last_offset() {
        let last = entries().last().unwrap();
        let far_future_tai = Tai::from_nanos(last.tai_effective_ns + 20 * 365 * 86_400_000_000_000);
        assert_eq!(
            far_future_tai.to_utc_nanos(),
            far_future_tai.as_nanos() - last.tai_utc_offset_seconds * 1_000_000_000
        );
    }

    #[test]
    fn tt_round_trips_and_matches_the_iau_constant() {
        let t = Tai::from_nanos(1_700_000_000_123_456_789);
        assert_eq!(t.to_tt_nanos(), t.as_nanos() + 32_184_000_000);
        assert_eq!(Tai::from_tt_nanos(t.to_tt_nanos()), t);
    }

    #[test]
    fn gps_round_trips_and_matches_the_constant_offset() {
        let t = Tai::from_nanos(1_700_000_000_123_456_789);
        assert_eq!(t.to_gps_nanos(), t.as_nanos() - 19_000_000_000);
        assert_eq!(Tai::from_gps_nanos(t.to_gps_nanos()), t);
    }

    #[test]
    fn a1_mjd_of_the_tai_origin_matches_the_documented_constant() {
        // Tai(0) -> A1 ns = 34_381_700 -> days since the Unix epoch's MJD.
        let mjd = Tai::from_nanos(0).to_a1_mjd();
        let expected = 10_587.5 + 34_381_700.0 / 86_400_000_000_000.0;
        assert!((mjd - expected).abs() < 1e-15, "{mjd} vs {expected}");
    }

    #[test]
    fn a1_mjd_round_trips_within_a_microsecond() {
        // f64 days at present-day magnitudes carry roughly microsecond resolution (ADR-001
        // "Alternatives considered"); this is the realistic bar for a round trip through it.
        for ns in [
            0_i64,
            1_700_000_000_000_000_000,
            -1_700_000_000_000_000_000,
            63_072_010_000_000_000, // first leap-second boundary
        ] {
            let t = Tai::from_nanos(ns);
            let back = Tai::from_a1_mjd(t.to_a1_mjd());
            let residual_ns = (back.as_nanos() - t.as_nanos()).abs();
            assert!(residual_ns < 1_000, "residual {residual_ns} ns for {ns}");
        }
    }
}
