# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import authority_pb2 as altavista_dot_v1_dot_authority__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altavista/v1/authority_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandAuthorityServiceStub:
    """The command authority service: propose, check, authorize, dispatch, ack, query, and ledger
    verify, over the state machine and ledger `crates/av-command`'s library modules already
    implement (`crates/av-command/src/service.rs`). See each RPC's own request message doc
    comment above for what it does and does not verify; see that module's own doc comment for
    the `tonic::Status` code chosen for every refusal.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Propose = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Propose',
                request_serializer=altavista_dot_v1_dot_authority__pb2.ProposeRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Check',
                request_serializer=altavista_dot_v1_dot_authority__pb2.CheckRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Authorize = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Authorize',
                request_serializer=altavista_dot_v1_dot_authority__pb2.AuthorizeRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Dispatch = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Dispatch',
                request_serializer=altavista_dot_v1_dot_authority__pb2.DispatchRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Ack',
                request_serializer=altavista_dot_v1_dot_authority__pb2.AckRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/Query',
                request_serializer=altavista_dot_v1_dot_authority__pb2.QueryRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.VerifyLedger = channel.unary_unary(
                '/altavista.v1.CommandAuthorityService/VerifyLedger',
                request_serializer=altavista_dot_v1_dot_authority__pb2.VerifyLedgerRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_authority__pb2.VerifyLedgerResponse.FromString,
                _registered_method=True)


class CommandAuthorityServiceServicer:
    """The command authority service: propose, check, authorize, dispatch, ack, query, and ledger
    verify, over the state machine and ledger `crates/av-command`'s library modules already
    implement (`crates/av-command/src/service.rs`). See each RPC's own request message doc
    comment above for what it does and does not verify; see that module's own doc comment for
    the `tonic::Status` code chosen for every refusal.
    """

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyLedger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandAuthorityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.ProposeRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.CheckRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.SerializeToString,
            ),
            'Authorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Authorize,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.AuthorizeRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.SerializeToString,
            ),
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.DispatchRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.AckRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.CommandResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.QueryRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.QueryResponse.SerializeToString,
            ),
            'VerifyLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyLedger,
                    request_deserializer=altavista_dot_v1_dot_authority__pb2.VerifyLedgerRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_authority__pb2.VerifyLedgerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altavista.v1.CommandAuthorityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altavista.v1.CommandAuthorityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommandAuthorityService:
    """The command authority service: propose, check, authorize, dispatch, ack, query, and ledger
    verify, over the state machine and ledger `crates/av-command`'s library modules already
    implement (`crates/av-command/src/service.rs`). See each RPC's own request message doc
    comment above for what it does and does not verify; see that module's own doc comment for
    the `tonic::Status` code chosen for every refusal.
    """

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Propose',
            altavista_dot_v1_dot_authority__pb2.ProposeRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Check',
            altavista_dot_v1_dot_authority__pb2.CheckRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Authorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Authorize',
            altavista_dot_v1_dot_authority__pb2.AuthorizeRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Dispatch',
            altavista_dot_v1_dot_authority__pb2.DispatchRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Ack',
            altavista_dot_v1_dot_authority__pb2.AckRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/Query',
            altavista_dot_v1_dot_authority__pb2.QueryRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.CommandAuthorityService/VerifyLedger',
            altavista_dot_v1_dot_authority__pb2.VerifyLedgerRequest.SerializeToString,
            altavista_dot_v1_dot_authority__pb2.VerifyLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
