# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/authority.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/authority.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import command_pb2 as altavista_dot_v1_dot_command__pb2
from . import envelope_pb2 as altavista_dot_v1_dot_envelope__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61ltavista/v1/authority.proto\x12\x0c\x61ltavista.v1\x1a\x1a\x61ltavista/v1/command.proto\x1a\x1b\x61ltavista/v1/envelope.proto\"\xa5\x01\n\x0fPolicyInputRate\x12I\n\x0f\x63ounts_by_class\x18\x01 \x03(\x0b\x32\x30.altavista.v1.PolicyInputRate.CountsByClassEntry\x12\x11\n\twindow_ns\x18\x02 \x01(\x03\x1a\x34\n\x12\x43ountsByClassEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\xc4\x01\n\x0bPolicyInput\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x15\n\rcommand_class\x18\x03 \x01(\t\x12\x11\n\thazardous\x18\x04 \x01(\x08\x12\x13\n\x0b\x65nvelope_id\x18\x05 \x01(\t\x12\"\n\x05label\x18\x06 \x01(\x0b\x32\x13.altavista.v1.Label\x12+\n\x04rate\x18\x07 \x01(\x0b\x32\x1d.altavista.v1.PolicyInputRate\"\x8f\x01\n\x0ePolicyDecision\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x01 \x01(\t\x12\r\n\x05\x61llow\x18\x02 \x01(\x08\x12\x13\n\x0bpolicy_hash\x18\x03 \x01(\t\x12\x0f\n\x07reasons\x18\x04 \x03(\t\x12\x19\n\x11matched_rule_path\x18\x05 \x01(\t\x12\x18\n\x10\x65valuated_tai_ns\x18\x06 \x01(\x03\"\xd8\x01\n\x0cLedgerRecord\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x11\n\tpartition\x18\x02 \x01(\t\x12\x11\n\tprev_hash\x18\x03 \x01(\x0c\x12\x0c\n\x04hash\x18\x04 \x01(\x0c\x12\x0e\n\x06tai_ns\x18\x05 \x01(\x03\x12\x12\n\ncommand_id\x18\x06 \x01(\t\x12\x33\n\ntransition\x18\x07 \x01(\x0b\x32\x1f.altavista.v1.CommandTransition\x12.\n\x08\x64\x65\x63ision\x18\x08 \x01(\x0b\x32\x1c.altavista.v1.PolicyDecisionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.authority_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICYINPUTRATE_COUNTSBYCLASSENTRY']._loaded_options = None
  _globals['_POLICYINPUTRATE_COUNTSBYCLASSENTRY']._serialized_options = b'8\001'
  _globals['_POLICYINPUTRATE']._serialized_start=104
  _globals['_POLICYINPUTRATE']._serialized_end=269
  _globals['_POLICYINPUTRATE_COUNTSBYCLASSENTRY']._serialized_start=217
  _globals['_POLICYINPUTRATE_COUNTSBYCLASSENTRY']._serialized_end=269
  _globals['_POLICYINPUT']._serialized_start=272
  _globals['_POLICYINPUT']._serialized_end=468
  _globals['_POLICYDECISION']._serialized_start=471
  _globals['_POLICYDECISION']._serialized_end=614
  _globals['_LEDGERRECORD']._serialized_start=617
  _globals['_LEDGERRECORD']._serialized_end=833
# @@protoc_insertion_point(module_scope)
