# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import board_pb2 as altavista_dot_v1_dot_board__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altavista/v1/board_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BoardEdgeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PowerCycle = channel.unary_unary(
                '/altavista.v1.BoardEdgeService/PowerCycle',
                request_serializer=altavista_dot_v1_dot_board__pb2.PowerCycleRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_board__pb2.PowerCycleResponse.FromString,
                _registered_method=True)
        self.BoardIoLogHead = channel.unary_unary(
                '/altavista.v1.BoardEdgeService/BoardIoLogHead',
                request_serializer=altavista_dot_v1_dot_board__pb2.BoardIoLogHeadRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_board__pb2.BoardIoLogHeadResponse.FromString,
                _registered_method=True)


class BoardEdgeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PowerCycle(self, request, context):
        """Run the edge node's configured power-control channel to power-cycle the board, once,
        and report what happened. The edge service refuses without running anything when it has
        no channel configured, when `power_control` differs from its own configured channel, or
        when `edge_node_id` differs from its own (a refusal is a normal response with outcome
        `BOARD_POWER_CYCLE_OUTCOME_REFUSED`, never a gRPC error). A gRPC error means the
        operation could not be carried out or recorded at all (for example the edge service's
        board I/O log has failed, so nothing may happen that the log cannot hold).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BoardIoLogHead(self, request, context):
        """Report where the edge service's board I/O log ends right now: the number of records
        durably appended, the hash of the last one (the chain head) and who signs the log. The
        kernel asks once, after the last STEP of a board-bound run and before its SHUTDOWN, and
        pins the answer in the run's products; a hash chain cannot show that records were removed
        from its end, so a replay compares the log it is given with that pin. Read only: it
        writes no record. The edge service answers `FAILED_PRECONDITION` when its log has failed,
        when no BIND has named a run yet, or when `run_id` / `instance` differ from the run and
        instance the kernel's BIND named (the head of another run's log is not this run's).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BoardEdgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PowerCycle': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerCycle,
                    request_deserializer=altavista_dot_v1_dot_board__pb2.PowerCycleRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_board__pb2.PowerCycleResponse.SerializeToString,
            ),
            'BoardIoLogHead': grpc.unary_unary_rpc_method_handler(
                    servicer.BoardIoLogHead,
                    request_deserializer=altavista_dot_v1_dot_board__pb2.BoardIoLogHeadRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_board__pb2.BoardIoLogHeadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altavista.v1.BoardEdgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altavista.v1.BoardEdgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BoardEdgeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PowerCycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.BoardEdgeService/PowerCycle',
            altavista_dot_v1_dot_board__pb2.PowerCycleRequest.SerializeToString,
            altavista_dot_v1_dot_board__pb2.PowerCycleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BoardIoLogHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.BoardEdgeService/BoardIoLogHead',
            altavista_dot_v1_dot_board__pb2.BoardIoLogHeadRequest.SerializeToString,
            altavista_dot_v1_dot_board__pb2.BoardIoLogHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
