# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/board.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/board.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61ltavista/v1/board.proto\x12\x0c\x61ltavista.v1\"\x84\x01\n\x11PowerCycleRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x10\n\x08instance\x18\x02 \x01(\t\x12\x10\n\x08\x66\x61ult_id\x18\x03 \x01(\t\x12\x0e\n\x06tai_ns\x18\x04 \x01(\x03\x12\x14\n\x0c\x65\x64ge_node_id\x18\x05 \x01(\t\x12\x15\n\rpower_control\x18\x06 \x01(\t\"\xe2\x02\n\x12PowerCycleResponse\x12\x35\n\x07outcome\x18\x01 \x01(\x0e\x32$.altavista.v1.BoardPowerCycleOutcome\x12\x35\n\x07refusal\x18\x02 \x01(\x0e\x32$.altavista.v1.BoardPowerCycleRefusal\x12\x35\n\x07\x66\x61ilure\x18\x03 \x01(\x0e\x32$.altavista.v1.BoardPowerCycleFailure\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\x12\x13\n\x0b\x65xit_status\x18\x05 \x01(\x05\x12\x0e\n\x06signal\x18\x06 \x01(\x05\x12\x13\n\x0bstderr_tail\x18\x07 \x01(\t\x12\x15\n\rpower_control\x18\x08 \x01(\t\x12\x13\n\x0b\x64uration_ns\x18\t \x01(\x03\x12\x17\n\x0fstarted_unix_ns\x18\n \x01(\x03\x12\x18\n\x10\x66inished_unix_ns\x18\x0b \x01(\x03*\xb9\x01\n\x16\x42oardPowerCycleOutcome\x12)\n%BOARD_POWER_CYCLE_OUTCOME_UNSPECIFIED\x10\x00\x12\'\n#BOARD_POWER_CYCLE_OUTCOME_PERFORMED\x10\x01\x12%\n!BOARD_POWER_CYCLE_OUTCOME_REFUSED\x10\x02\x12$\n BOARD_POWER_CYCLE_OUTCOME_FAILED\x10\x03*\xcf\x01\n\x16\x42oardPowerCycleRefusal\x12)\n%BOARD_POWER_CYCLE_REFUSAL_UNSPECIFIED\x10\x00\x12(\n$BOARD_POWER_CYCLE_REFUSAL_NO_CHANNEL\x10\x01\x12.\n*BOARD_POWER_CYCLE_REFUSAL_CHANNEL_MISMATCH\x10\x02\x12\x30\n,BOARD_POWER_CYCLE_REFUSAL_EDGE_NODE_MISMATCH\x10\x03*\xe2\x01\n\x16\x42oardPowerCycleFailure\x12)\n%BOARD_POWER_CYCLE_FAILURE_UNSPECIFIED\x10\x00\x12#\n\x1f\x42OARD_POWER_CYCLE_FAILURE_SPAWN\x10\x01\x12)\n%BOARD_POWER_CYCLE_FAILURE_EXIT_STATUS\x10\x02\x12&\n\"BOARD_POWER_CYCLE_FAILURE_SIGNALED\x10\x03\x12%\n!BOARD_POWER_CYCLE_FAILURE_TIMEOUT\x10\x04\x32\x63\n\x10\x42oardEdgeService\x12O\n\nPowerCycle\x12\x1f.altavista.v1.PowerCycleRequest\x1a .altavista.v1.PowerCycleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.board_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOARDPOWERCYCLEOUTCOME']._serialized_start=535
  _globals['_BOARDPOWERCYCLEOUTCOME']._serialized_end=720
  _globals['_BOARDPOWERCYCLEREFUSAL']._serialized_start=723
  _globals['_BOARDPOWERCYCLEREFUSAL']._serialized_end=930
  _globals['_BOARDPOWERCYCLEFAILURE']._serialized_start=933
  _globals['_BOARDPOWERCYCLEFAILURE']._serialized_end=1159
  _globals['_POWERCYCLEREQUEST']._serialized_start=43
  _globals['_POWERCYCLEREQUEST']._serialized_end=175
  _globals['_POWERCYCLERESPONSE']._serialized_start=178
  _globals['_POWERCYCLERESPONSE']._serialized_end=532
  _globals['_BOARDEDGESERVICE']._serialized_start=1161
  _globals['_BOARDEDGESERVICE']._serialized_end=1260
# @@protoc_insertion_point(module_scope)
