# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dynamics_service_pb2 as altavista_dot_v1_dot_dynamics__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altavista/v1/dynamics_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DynamicsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/altavista.v1.DynamicsService/Describe',
                request_serializer=altavista_dot_v1_dot_dynamics__service__pb2.DescribeRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.Derivatives = channel.unary_unary(
                '/altavista.v1.DynamicsService/Derivatives',
                request_serializer=altavista_dot_v1_dot_dynamics__service__pb2.DerivativesRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.DerivativesResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/altavista.v1.DynamicsService/Step',
                request_serializer=altavista_dot_v1_dot_dynamics__service__pb2.StepRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Propagate = channel.unary_unary(
                '/altavista.v1.DynamicsService/Propagate',
                request_serializer=altavista_dot_v1_dot_dynamics__service__pb2.PropagateRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.PropagateResponse.FromString,
                _registered_method=True)
        self.Solve = channel.unary_unary(
                '/altavista.v1.DynamicsService/Solve',
                request_serializer=altavista_dot_v1_dot_dynamics__service__pb2.SolveRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.SolveResponse.FromString,
                _registered_method=True)


class DynamicsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Derivatives(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propagate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Solve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamicsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.DescribeRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_dynamics__service__pb2.ModelInfo.SerializeToString,
            ),
            'Derivatives': grpc.unary_unary_rpc_method_handler(
                    servicer.Derivatives,
                    request_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.DerivativesRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_dynamics__service__pb2.DerivativesResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.StepRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_dynamics__service__pb2.StepResponse.SerializeToString,
            ),
            'Propagate': grpc.unary_unary_rpc_method_handler(
                    servicer.Propagate,
                    request_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.PropagateRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_dynamics__service__pb2.PropagateResponse.SerializeToString,
            ),
            'Solve': grpc.unary_unary_rpc_method_handler(
                    servicer.Solve,
                    request_deserializer=altavista_dot_v1_dot_dynamics__service__pb2.SolveRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_dynamics__service__pb2.SolveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altavista.v1.DynamicsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altavista.v1.DynamicsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DynamicsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.DynamicsService/Describe',
            altavista_dot_v1_dot_dynamics__service__pb2.DescribeRequest.SerializeToString,
            altavista_dot_v1_dot_dynamics__service__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Derivatives(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.DynamicsService/Derivatives',
            altavista_dot_v1_dot_dynamics__service__pb2.DerivativesRequest.SerializeToString,
            altavista_dot_v1_dot_dynamics__service__pb2.DerivativesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.DynamicsService/Step',
            altavista_dot_v1_dot_dynamics__service__pb2.StepRequest.SerializeToString,
            altavista_dot_v1_dot_dynamics__service__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propagate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.DynamicsService/Propagate',
            altavista_dot_v1_dot_dynamics__service__pb2.PropagateRequest.SerializeToString,
            altavista_dot_v1_dot_dynamics__service__pb2.PropagateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Solve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.DynamicsService/Solve',
            altavista_dot_v1_dot_dynamics__service__pb2.SolveRequest.SerializeToString,
            altavista_dot_v1_dot_dynamics__service__pb2.SolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
