# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import edge_pb2 as altavista_dot_v1_dot_edge__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altavista/v1/edge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdgeIngestStub:
    """The ingest boundary's gRPC service (E3b, question 202). Plaintext on loopback within one
    host (`crates/av-ingest/src/server.rs` refuses a non-loopback bind address at load with
    a typed error, mirroring `crates/av-kernel/src/drm/binding.rs::is_loopback_address`'s own
    refusal for the kernel's lockstep endpoint); a service-owned nginx mTLS front is the
    only sanctioned way a plugin reaches this service from another host.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Announce = channel.unary_unary(
                '/altavista.v1.EdgeIngest/Announce',
                request_serializer=altavista_dot_v1_dot_edge__pb2.PluginManifest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_edge__pb2.ManifestAck.FromString,
                _registered_method=True)
        self.Submit = channel.stream_stream(
                '/altavista.v1.EdgeIngest/Submit',
                request_serializer=altavista_dot_v1_dot_edge__pb2.MeasurementBatch.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_edge__pb2.BatchVerdict.FromString,
                _registered_method=True)
        self.GetEvidence = channel.unary_unary(
                '/altavista.v1.EdgeIngest/GetEvidence',
                request_serializer=altavista_dot_v1_dot_edge__pb2.EvidenceRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_edge__pb2.EvidenceResponse.FromString,
                _registered_method=True)
        self.VerifyLedger = channel.unary_unary(
                '/altavista.v1.EdgeIngest/VerifyLedger',
                request_serializer=altavista_dot_v1_dot_edge__pb2.VerifyRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_edge__pb2.VerifyResponse.FromString,
                _registered_method=True)


class EdgeIngestServicer:
    """The ingest boundary's gRPC service (E3b, question 202). Plaintext on loopback within one
    host (`crates/av-ingest/src/server.rs` refuses a non-loopback bind address at load with
    a typed error, mirroring `crates/av-kernel/src/drm/binding.rs::is_loopback_address`'s own
    refusal for the kernel's lockstep endpoint); a service-owned nginx mTLS front is the
    only sanctioned way a plugin reaches this service from another host.
    """

    def Announce(self, request, context):
        """The plugin manifest handshake -- must succeed for a `producer_id` before `Submit` is
        ever accepted for it. "Announced" is scoped to the serving process instance's
        lifetime, not to a TCP connection (see `MANIFEST_REFUSAL_MANIFEST_MISMATCH`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Submit(self, request_iterator, context):
        """The batch stream: one `BatchVerdict` per `MeasurementBatch`, in order. A batch whose
        `producer_id` never successfully called `Announce` on this serving process is refused
        (`FAILED_PRECONDITION`) before it is looked at.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvidence(self, request, context):
        """The evidence surface, over the wire, matching `GET /admin/api/evidence`'s content
        exactly (`crates/av-ingest/src/admin.rs`).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyLedger(self, request, context):
        """Per-partition chain verification, over the wire, matching `GET
        /admin/api/evidence/verify`'s content exactly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=altavista_dot_v1_dot_edge__pb2.PluginManifest.FromString,
                    response_serializer=altavista_dot_v1_dot_edge__pb2.ManifestAck.SerializeToString,
            ),
            'Submit': grpc.stream_stream_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=altavista_dot_v1_dot_edge__pb2.MeasurementBatch.FromString,
                    response_serializer=altavista_dot_v1_dot_edge__pb2.BatchVerdict.SerializeToString,
            ),
            'GetEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvidence,
                    request_deserializer=altavista_dot_v1_dot_edge__pb2.EvidenceRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_edge__pb2.EvidenceResponse.SerializeToString,
            ),
            'VerifyLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyLedger,
                    request_deserializer=altavista_dot_v1_dot_edge__pb2.VerifyRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_edge__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altavista.v1.EdgeIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altavista.v1.EdgeIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdgeIngest:
    """The ingest boundary's gRPC service (E3b, question 202). Plaintext on loopback within one
    host (`crates/av-ingest/src/server.rs` refuses a non-loopback bind address at load with
    a typed error, mirroring `crates/av-kernel/src/drm/binding.rs::is_loopback_address`'s own
    refusal for the kernel's lockstep endpoint); a service-owned nginx mTLS front is the
    only sanctioned way a plugin reaches this service from another host.
    """

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.EdgeIngest/Announce',
            altavista_dot_v1_dot_edge__pb2.PluginManifest.SerializeToString,
            altavista_dot_v1_dot_edge__pb2.ManifestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Submit(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/altavista.v1.EdgeIngest/Submit',
            altavista_dot_v1_dot_edge__pb2.MeasurementBatch.SerializeToString,
            altavista_dot_v1_dot_edge__pb2.BatchVerdict.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.EdgeIngest/GetEvidence',
            altavista_dot_v1_dot_edge__pb2.EvidenceRequest.SerializeToString,
            altavista_dot_v1_dot_edge__pb2.EvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.EdgeIngest/VerifyLedger',
            altavista_dot_v1_dot_edge__pb2.VerifyRequest.SerializeToString,
            altavista_dot_v1_dot_edge__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
