# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/envelope.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61ltavista/v1/envelope.proto\x12\x0c\x61ltavista.v1\x1a\x19google/protobuf/any.proto\")\n\x05Label\x12\x0f\n\x07marking\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61veats\x18\x02 \x03(\t\"\xae\x01\n\x08\x45nvelope\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x13\n\x0bproducer_id\x18\x02 \x01(\t\x12\"\n\x05label\x18\x03 \x01(\x0b\x32\x13.altavista.v1.Label\x12\x14\n\x0c\x65vent_tai_ns\x18\x04 \x01(\x03\x12\x17\n\x0fproduced_tai_ns\x18\x05 \x01(\x03\x12\x10\n\x08trace_id\x18\x06 \x01(\t\x12\x14\n\x0cpayload_type\x18\x07 \x01(\t\"_\n\x0c\x42\x61tchMessage\x12(\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\x16.altavista.v1.Envelope\x12%\n\x07payload\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xc9\x01\n\x05\x42\x61tch\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x13\n\x0bproducer_id\x18\x02 \x01(\t\x12\"\n\x05label\x18\x03 \x01(\x0b\x32\x13.altavista.v1.Label\x12\x10\n\x08sequence\x18\x04 \x01(\x04\x12,\n\x08messages\x18\x05 \x03(\x0b\x32\x1a.altavista.v1.BatchMessage\x12\x1a\n\x12\x66irst_event_tai_ns\x18\x06 \x01(\x03\x12\x19\n\x11last_event_tai_ns\x18\x07 \x01(\x03\"l\n\x0bSignedBatch\x12\r\n\x05\x62\x61tch\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x1a\n\x12signer_cert_sha256\x18\x03 \x01(\t\x12\x11\n\tprev_hash\x18\x04 \x01(\x0c\x12\x0c\n\x04hash\x18\x05 \x01(\x0c\"q\n\x11\x43hainVerification\x12\x13\n\x0bproducer_id\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x12\x0f\n\x07\x63hecked\x18\x03 \x01(\x04\x12\x1a\n\x12\x62roken_at_sequence\x18\x04 \x01(\x04\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABEL']._serialized_start=72
  _globals['_LABEL']._serialized_end=113
  _globals['_ENVELOPE']._serialized_start=116
  _globals['_ENVELOPE']._serialized_end=290
  _globals['_BATCHMESSAGE']._serialized_start=292
  _globals['_BATCHMESSAGE']._serialized_end=387
  _globals['_BATCH']._serialized_start=390
  _globals['_BATCH']._serialized_end=591
  _globals['_SIGNEDBATCH']._serialized_start=593
  _globals['_SIGNEDBATCH']._serialized_end=701
  _globals['_CHAINVERIFICATION']._serialized_start=703
  _globals['_CHAINVERIFICATION']._serialized_end=816
# @@protoc_insertion_point(module_scope)
