# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/heavy.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/heavy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import entity_pb2 as altavista_dot_v1_dot_entity__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61ltavista/v1/heavy.proto\x12\x0c\x61ltavista.v1\x1a\x19\x61ltavista/v1/entity.proto\"M\n\x07GeoBbox\x12\x0f\n\x07min_lon\x18\x01 \x01(\x01\x12\x0f\n\x07min_lat\x18\x02 \x01(\x01\x12\x0f\n\x07max_lon\x18\x03 \x01(\x01\x12\x0f\n\x07max_lat\x18\x04 \x01(\x01\"\x92\x01\n\x0c\x43\x61talogQuery\x12#\n\x04\x62\x62ox\x18\x01 \x01(\x0b\x32\x15.altavista.v1.GeoBbox\x12*\n\x04time\x18\x02 \x01(\x0b\x32\x1c.altavista.v1.TemporalExtent\x12\x12\n\nmedia_type\x18\x03 \x01(\t\x12\x0e\n\x06job_id\x18\x04 \x01(\t\x12\r\n\x05limit\x18\x05 \x01(\r\"\x87\x01\n\rCatalogRecord\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\x12%\n\x05\x61sset\x18\x02 \x01(\x0b\x32\x16.altavista.v1.AssetRef\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x16\n\x0e\x63reated_tai_ns\x18\x04 \x01(\x03\x12\x15\n\rfootprint_wkt\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.heavy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOBBOX']._serialized_start=69
  _globals['_GEOBBOX']._serialized_end=146
  _globals['_CATALOGQUERY']._serialized_start=149
  _globals['_CATALOGQUERY']._serialized_end=295
  _globals['_CATALOGRECORD']._serialized_start=298
  _globals['_CATALOGRECORD']._serialized_end=433
# @@protoc_insertion_point(module_scope)
