# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import lockstep_pb2 as altavista_dot_v1_dot_lockstep__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in altavista/v1/lockstep_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LockstepServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bind = channel.unary_unary(
                '/altavista.v1.LockstepService/Bind',
                request_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepBindRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepBindResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/altavista.v1.LockstepService/Step',
                request_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepStepRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepStepResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/altavista.v1.LockstepService/Reset',
                request_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepResetRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepResetResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/altavista.v1.LockstepService/Shutdown',
                request_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownRequest.SerializeToString,
                response_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownResponse.FromString,
                _registered_method=True)


class LockstepServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Bind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockstepServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bind': grpc.unary_unary_rpc_method_handler(
                    servicer.Bind,
                    request_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepBindRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepBindResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepStepRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepStepResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepResetRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepResetResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownRequest.FromString,
                    response_serializer=altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'altavista.v1.LockstepService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('altavista.v1.LockstepService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockstepService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.LockstepService/Bind',
            altavista_dot_v1_dot_lockstep__pb2.LockstepBindRequest.SerializeToString,
            altavista_dot_v1_dot_lockstep__pb2.LockstepBindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.LockstepService/Step',
            altavista_dot_v1_dot_lockstep__pb2.LockstepStepRequest.SerializeToString,
            altavista_dot_v1_dot_lockstep__pb2.LockstepStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.LockstepService/Reset',
            altavista_dot_v1_dot_lockstep__pb2.LockstepResetRequest.SerializeToString,
            altavista_dot_v1_dot_lockstep__pb2.LockstepResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/altavista.v1.LockstepService/Shutdown',
            altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownRequest.SerializeToString,
            altavista_dot_v1_dot_lockstep__pb2.LockstepShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
