# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/packet.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as altavista_dot_v1_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61ltavista/v1/packet.proto\x12\x0c\x61ltavista.v1\x1a\x17\x61ltavista/v1/core.proto\"\xc0\x01\n\x0bPacketField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nbit_offset\x18\x02 \x01(\r\x12\x11\n\tbit_width\x18\x03 \x01(\r\x12+\n\x04type\x18\x04 \x01(\x0e\x32\x1d.altavista.v1.PacketFieldType\x12 \n\x04unit\x18\x05 \x01(\x0e\x32\x12.altavista.v1.Unit\x12\r\n\x05scale\x18\x06 \x01(\x01\x12\x0e\n\x06offset\x18\x07 \x01(\x01\x12\x0e\n\x06target\x18\x08 \x01(\t\"\xb4\x01\n\x0bPacketCodec\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61pid\x18\x02 \x01(\r\x12\x12\n\nis_command\x18\x03 \x01(\x08\x12\x1e\n\x16secondary_header_bytes\x18\x04 \x01(\r\x12)\n\x06\x66ields\x18\x05 \x03(\x0b\x32\x19.altavista.v1.PacketField\x12\x17\n\x0fuser_data_bytes\x18\x06 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t*\xc6\x01\n\x0fPacketFieldType\x12!\n\x1dPACKET_FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16PACKET_FIELD_TYPE_UINT\x10\x01\x12\x19\n\x15PACKET_FIELD_TYPE_INT\x10\x02\x12\x1d\n\x19PACKET_FIELD_TYPE_FLOAT32\x10\x03\x12\x1d\n\x19PACKET_FIELD_TYPE_FLOAT64\x10\x04\x12\x1b\n\x17PACKET_FIELD_TYPE_BYTES\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKETFIELDTYPE']._serialized_start=447
  _globals['_PACKETFIELDTYPE']._serialized_end=645
  _globals['_PACKETFIELD']._serialized_start=69
  _globals['_PACKETFIELD']._serialized_end=261
  _globals['_PACKETCODEC']._serialized_start=264
  _globals['_PACKETCODEC']._serialized_end=444
# @@protoc_insertion_point(module_scope)
