# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: altavista/v1/run.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'altavista/v1/run.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import core_pb2 as altavista_dot_v1_dot_core__pb2
from . import trajectory_pb2 as altavista_dot_v1_dot_trajectory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ltavista/v1/run.proto\x12\x0c\x61ltavista.v1\x1a\x17\x61ltavista/v1/core.proto\x1a\x1d\x61ltavista/v1/trajectory.proto\"l\n\x0bScoreResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12 \n\x04unit\x18\x03 \x01(\x0e\x32\x12.altavista.v1.Unit\x12\x13\n\x06passed\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\t\n\x07_passed\"\x87\x04\n\x0bRunProducts\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x41\n\x0ctrajectories\x18\x02 \x03(\x0b\x32+.altavista.v1.RunProducts.TrajectoriesEntry\x12#\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x13.altavista.v1.Event\x12\x35\n\x06scores\x18\x04 \x03(\x0b\x32%.altavista.v1.RunProducts.ScoresEntry\x12,\n\nprovenance\x18\x05 \x01(\x0b\x32\x18.altavista.v1.Provenance\x12\"\n\x1a\x64ropped_in_flight_messages\x18\x06 \x01(\x04\x12-\n\x06\x66rames\x18\x07 \x03(\x0b\x32\x1d.altavista.v1.FrameDefinition\x12/\n\x0cmeasurements\x18\x08 \x03(\x0b\x32\x19.altavista.v1.Measurement\x1aM\n\x11TrajectoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.altavista.v1.Trajectory:\x02\x38\x01\x1aH\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.altavista.v1.ScoreResult:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'altavista.v1.run_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNPRODUCTS_TRAJECTORIESENTRY']._loaded_options = None
  _globals['_RUNPRODUCTS_TRAJECTORIESENTRY']._serialized_options = b'8\001'
  _globals['_RUNPRODUCTS_SCORESENTRY']._loaded_options = None
  _globals['_RUNPRODUCTS_SCORESENTRY']._serialized_options = b'8\001'
  _globals['_SCORERESULT']._serialized_start=96
  _globals['_SCORERESULT']._serialized_end=204
  _globals['_RUNPRODUCTS']._serialized_start=207
  _globals['_RUNPRODUCTS']._serialized_end=726
  _globals['_RUNPRODUCTS_TRAJECTORIESENTRY']._serialized_start=575
  _globals['_RUNPRODUCTS_TRAJECTORIESENTRY']._serialized_end=652
  _globals['_RUNPRODUCTS_SCORESENTRY']._serialized_start=654
  _globals['_RUNPRODUCTS_SCORESENTRY']._serialized_end=726
# @@protoc_insertion_point(module_scope)
