//! Every command-authority transition -- and every refused attempt -- as one RFC 5424
//! syslog-format line to a configured sink (A2.2, `docs/aiplane-plan.md` milestone A2's
//! second half; ADR-004's "Evidence, verbatim from P0" section: "forwards audit events to
//! syslog/SIEM when `[audit]` is configured"; `docs/open-questions.md` question 54's "SIEM
//! export of the decision trail").
//!
//! # The exact line, field by field (RFC 5424)
//!
//! ```text
//! <PRIVAL>1 TIMESTAMP HOSTNAME APP-NAME PROCID MSGID STRUCTURED-DATA MSG
//! ```
//!
//! - **`<PRIVAL>1`** -- RFC 5424 section 6.2.1 (PRI) and 6.2.2 (VERSION). `PRIVAL = Facility *
//!   8 + Severity`. `Facility` is fixed at `16` (`local0`, section 6.2.1's Table 1) -- this
//!   crate is not a standard syslog subsystem, so `local0` (the first of the eight
//!   locally-defined facilities) is the correct, deterministic choice, never a value that
//!   depends on anything about the run. `Severity` is [`Severity::Informational`] (`6`) for a
//!   real transition and [`Severity::Warning`] (`4`) for a refused attempt -- "a denied
//!   authorization attempt is exactly what a SIEM needs to see" (this task's own brief), so a
//!   refusal is never emitted at the same, easy-to-filter-out severity as routine success.
//!   `VERSION` is the literal `1` RFC 5424 fixes (section 6.2.2).
//! - **`TIMESTAMP`** -- section 6.2.3, `FULL-DATE "T" FULL-TIME`, rendered
//!   `YYYY-MM-DDTHH:MM:SS.ffffffZ`. Six fractional digits (microseconds) -- `TIME-SECFRAC`'s
//!   grammar (`"." 1*6DIGIT`) allows at most six, so the injected clock's trailing three
//!   nanosecond digits are truncated, never rounded (deterministic: the same `tai_ns` always
//!   truncates to the same six digits). **Always from the injected [`crate::clock::Clock`]**
//!   ([`AuditEvent::tai_ns`], never a second, independent wall-clock read) -- this is what
//!   makes two identical runs produce identical audit lines, the acceptance property this
//!   task's brief names explicitly. The UTC conversion is
//!   `av_cdm::time::Tai::from_nanos(tai_ns).to_utc_nanos()`, the identical TAI->UTC path this
//!   crate's own `crate::clock::SystemClock` and `crate::oidc`'s claim conversions use -- no
//!   second, ad hoc time conversion anywhere in this crate.
//! - **`HOSTNAME`** -- section 6.2.4. The NILVALUE `"-"`, deliberately: this crate has no
//!   dependency that reads the real hostname (adding one purely for a log field would be a
//!   new, unvetted dependency this task's brief asks to avoid), and a real hostname would
//!   also be a second source of run-to-run variation this module's whole determinism
//!   guarantee is built to exclude -- the audit line names the *event*, not the *host it
//!   happened to run on this time*.
//! - **`APP-NAME`** -- section 6.2.5. The fixed literal `"av-command"`.
//! - **`PROCID`** -- section 6.2.6. The NILVALUE `"-"`, deliberately, for the same reason as
//!   `HOSTNAME`: RFC 5424 itself defines PROCID as "a value ... to identify ... which
//!   messages are automatically generated by the same process" -- useful for a live syslog
//!   daemon disambiguating concurrent processes, but a real OS PID varies by run and would
//!   break the byte-for-byte reproducibility this task's own acceptance test demands ("two
//!   identical runs produce identical audit lines"). Every reader that needs to know this was
//!   `av-command` already has `APP-NAME`; nothing here needs a second, run-varying id.
//! - **`MSGID`** -- section 6.2.7. The `CommandState` name (`"PROPOSED"`, `"CHECKED"`, ...;
//!   [`command_state_name`], exhaustive, no catch-all arm -- ADR-004's rule for every
//!   exhaustive match in this crate) for a real transition, or the literal `"REFUSED"` for a
//!   refused attempt that never reached a state edge at all.
//! - **`STRUCTURED-DATA`** -- section 6.3. One SD-ELEMENT, SD-ID `avCommand@32473` (the
//!   `@`-plus-Private-Enterprise-Number form section 6.3.2 recommends to avoid collisions;
//!   `32473` is IANA's own reserved example PEN, used the same way RFC 5424's own examples
//!   use it, since this crate has no registered PEN of its own), carrying whichever of these
//!   SD-PARAMs apply to this event -- "carries the command id, entity, class, state,
//!   principal, delegation id, decision id and policy hash where each applies" (this task's
//!   own brief): `commandId`, `entity`, `class`, `state`, `principal`, `delegationId`,
//!   `decisionId`, `policyHash`. "Applies" is read uniformly as "the value is non-empty" --
//!   `decisionId`/`policyHash` apply only to a `CHECKED`/`REJECTED` transition that carried a
//!   [`av_cdm::pb::PolicyDecision`]; `delegationId` applies only when a delegation was
//!   claimed; the rest apply to every event this module ever builds. Every PARAM-VALUE is
//!   escaped per section 6.3.3 ([`sd_escape`]: `\`, `"` and `]` each get a `\` prefix) --
//!   never raw-interpolated, since an entity id or a free-text reason could in principle
//!   contain any of those three characters. An event with no applicable param at all still
//!   emits a syntactically valid `[avCommand@32473]` (zero SD-PARAMs is legal per the
//!   grammar), never the STRUCTURED-DATA NILVALUE `"-"` -- this module's own SD-ID is always
//!   present so a reader can always identify which product emitted the element.
//! - **`MSG`** -- section 6.4. The free-text reason: the transition's own `CommandTransition.
//!   reason` (already single-line by construction in this crate -- `crate::authority::
//!   format_reason`/`crate::authz::format_authz_reason` never emit embedded newlines) for a
//!   real transition, or the refusing [`crate::authz::AuthzError`]/[`crate::oidc::TokenError`]/
//!   [`crate::state::CommandError`]'s own `Display` text for a refusal.
//!
//! # When no `[audit]` sink is configured
//!
//! [`AuditSinkConfig::Disabled`] -- the profile declares no `audit.sink_path`, or declares it
//! empty -- makes [`AuditWriter::write`] a **no-op that returns `Ok(())`**, explicitly, not an
//! accident of some other code path silently doing nothing: [`AuditWriter::open`] stores
//! `None` in place of an open file, and [`AuditWriter::write`]'s `match` has its own `None =>
//! Ok(())` arm, right next to the `Some(file) => { ... }` arm that does the real write --
//! there is no default/fallback branch doing double duty for both cases. This mirrors ADR-004's
//! own phrasing exactly ("forwards audit events to syslog/SIEM **when `[audit]` is
//! configured**") -- an unconfigured sink is a documented, deliberate deployment choice (e.g.
//! a dev/eval profile with no SIEM reachable), never a silent failure to write, and never a
//! reason to skip appending the transition to the ledger, which remains this crate's
//! retention mechanism regardless (see the next section).
//!
//! # Retention (question 54) is the ledger, not a second mechanism
//!
//! This module builds no retention, rotation or expiry policy of its own for the audit sink,
//! and that is deliberate, not a gap this task left open: `crates/av-command/src/ledger.rs`
//! already retains every transition forever (ADR-004: "for the engine and command services
//! the durable log itself is the ledger"; `docs/compliance/av-command/control-matrix.md`'s AU
//! 3.3.1 row already scores this as Met). The audit sink this module writes to is the *export*
//! half of question 54 ("retention plus SIEM export of the decision trail") -- a forwarding
//! copy for a SIEM to ingest, not a second store of record. **A file sink is not a SIEM**:
//! `docs/compliance/av-command/control-matrix.md`'s own row on this says so explicitly, and a
//! reviewer should read this module's file-sink implementation as "the SIEM-forwarding
//! interface exists and is tested," not "a SIEM integration was built."
//!
//! # A UDP/Unix-socket sink was not added
//!
//! This task's brief allows one "only if it costs nothing and is tested." A `File` sink is
//! the minimum this task's own tests need (a real artifact to read lines back from, byte for
//! byte); a UDP or Unix-domain-socket transport would add real, untested surface (packet-size
//! truncation for a very long structured-data element, `ENOTCONN`/`ECONNREFUSED` handling, a
//! syslog framing convention -- RFC 5425/6587 octet-counting versus non-transparent framing --
//! this module would then have to pick one of) for no test in this crate's own suite to
//! exercise, since nothing in this repository runs a receiving syslog daemon. Declared here,
//! not built silently as a half-tested extra.

use std::fs::OpenOptions;
use std::io::{self, Write as _};
use std::path::PathBuf;
use std::sync::Mutex;

use av_cdm::pb::{Command, CommandState, CommandTransition, PolicyDecision};
use av_cdm::time::Tai;

/// RFC 5424 section 6.2.1's severity values this module actually emits -- `Informational`
/// (`6`) for a real transition, `Warning` (`4`) for a refused attempt. Not every RFC 5424
/// severity is a variant here: this module only ever emits these two, and a match over this
/// enum elsewhere in the crate should stay exhaustive over exactly these two, not grow a
/// catch-all for severities this module never produces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Informational,
    Warning,
}

impl Severity {
    fn value(self) -> u16 {
        match self {
            Severity::Informational => 6,
            Severity::Warning => 4,
        }
    }
}

/// RFC 5424 section 6.2.1's Table 1, facility 16 (`local0`) -- see the module doc.
const FACILITY_LOCAL0: u16 = 16;
const APP_NAME: &str = "av-command";
/// RFC 5424 section 6.3.2's `@`-plus-PEN SD-ID form; `32473` is IANA's own reserved example
/// Private Enterprise Number (the same one RFC 5424's own examples use) -- see the module doc.
const SD_ID: &str = "avCommand@32473";

/// The `CommandState` name RFC 5424's `MSGID` carries for a real transition -- exhaustive,
/// no catch-all arm (ADR-004's rule for every exhaustive match in this crate).
pub fn command_state_name(state: CommandState) -> &'static str {
    match state {
        CommandState::Unspecified => "UNSPECIFIED",
        CommandState::Proposed => "PROPOSED",
        CommandState::Checked => "CHECKED",
        CommandState::Authorized => "AUTHORIZED",
        CommandState::Dispatched => "DISPATCHED",
        CommandState::Acked => "ACKED",
        CommandState::Rejected => "REJECTED",
        CommandState::Expired => "EXPIRED",
        CommandState::Failed => "FAILED",
    }
}

/// The literal `MSGID`/`state` value a refused attempt (no state edge ever attempted) uses --
/// distinct from every real `CommandState` name [`command_state_name`] produces.
pub const REFUSED: &str = "REFUSED";

/// Everything one audit line needs, independent of where it is written to. Built by
/// [`event_for_transition`] (a real, successful transition) or [`event_for_refusal`] (a
/// denied attempt) -- see each function's own doc.
#[derive(Debug, Clone)]
pub struct AuditEvent {
    /// Always from the injected `Clock` -- see the module doc's `TIMESTAMP` section.
    pub tai_ns: i64,
    pub severity: Severity,
    pub msg_id: String,
    pub command_id: String,
    pub entity: String,
    pub class: String,
    pub state: String,
    pub principal: String,
    pub delegation_id: String,
    pub decision_id: String,
    pub policy_hash: String,
    pub message: String,
}

/// The event for a real, successful transition -- `state`/`msg_id` from [`command_state_name`],
/// `decision_id`/`policy_hash` populated only when `decision` is `Some` (the `CHECKED`/
/// `REJECTED` case; see the module doc's `STRUCTURED-DATA` section).
pub fn event_for_transition(command: &Command, transition: &CommandTransition, decision: Option<&PolicyDecision>) -> AuditEvent {
    let state = CommandState::try_from(transition.state).unwrap_or(CommandState::Unspecified);
    let name = command_state_name(state);
    AuditEvent {
        tai_ns: transition.tai_ns,
        severity: Severity::Informational,
        msg_id: name.to_string(),
        command_id: command.id.clone(),
        entity: command.entity_id.clone(),
        class: command.command_class.clone(),
        state: name.to_string(),
        principal: transition.principal.clone(),
        delegation_id: transition.delegation_id.clone(),
        decision_id: decision.map(|d| d.decision_id.clone()).unwrap_or_default(),
        policy_hash: decision.map(|d| d.policy_hash.clone()).unwrap_or_default(),
        message: transition.reason.clone(),
    }
}

/// The event for a refused attempt -- no state edge was ever attempted, so there is no
/// `CommandTransition` to build from; every field is supplied by the caller directly. `state`/
/// `msg_id` are always [`REFUSED`], `severity` always [`Severity::Warning`]. Exactly seven
/// parameters -- at clippy's default `too_many_arguments` threshold, not over it, so this
/// needed no a lint-suppressing attribute and no grouping struct (unlike `crate::service::AuthzConfig`, which
/// exists for exactly that reason where a signature genuinely would have gone over).
pub fn event_for_refusal(tai_ns: i64, command_id: &str, entity: &str, class: &str, principal: &str, delegation_id: &str, message: &str) -> AuditEvent {
    AuditEvent {
        tai_ns,
        severity: Severity::Warning,
        msg_id: REFUSED.to_string(),
        command_id: command_id.to_string(),
        entity: entity.to_string(),
        class: class.to_string(),
        state: REFUSED.to_string(),
        principal: principal.to_string(),
        delegation_id: delegation_id.to_string(),
        decision_id: String::new(),
        policy_hash: String::new(),
        message: message.to_string(),
    }
}

/// RFC 5424 section 6.3.3's PARAM-VALUE escaping: `\`, `"` and `]` each get a `\` prefix.
fn sd_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            ']' => out.push_str("\\]"),
            _ => out.push(c),
        }
    }
    out
}

/// Howard Hinnant's `civil_from_days` (public domain,
/// <http://howardhinnant.github.io/date_algorithms.html>): the proleptic-Gregorian
/// (year, month, day) for `z`, days since the Unix epoch (`1970-01-01` is `z == 0`). Pure
/// integer arithmetic, total over every `i64` -- no float, no calendar library dependency.
fn civil_from_days(z: i64) -> (i64, u32, u32) {
    let z = z + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z - era * 146_097; // [0, 146096]
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let m = (if mp < 10 { mp + 3 } else { mp - 9 }) as u32; // [1, 12]
    let year = if m <= 2 { y + 1 } else { y };
    (year, m, d)
}

/// `YYYY-MM-DDTHH:MM:SS.ffffffZ` for `tai_ns` -- see the module doc's `TIMESTAMP` section for
/// the truncation-not-rounding rule and why this is the only conversion site.
fn format_timestamp(tai_ns: i64) -> String {
    let utc_ns = Tai::from_nanos(tai_ns).to_utc_nanos();
    let secs = utc_ns.div_euclid(1_000_000_000);
    let nanos = utc_ns.rem_euclid(1_000_000_000);
    let micros = nanos / 1_000;
    let days = secs.div_euclid(86_400);
    let secs_of_day = secs.rem_euclid(86_400);
    let (y, mo, d) = civil_from_days(days);
    let h = secs_of_day / 3_600;
    let mi = (secs_of_day % 3_600) / 60;
    let s = secs_of_day % 60;
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}.{micros:06}Z")
}

/// The exact RFC 5424 line for `event`, with **no** trailing newline (the caller appends
/// exactly one -- see [`AuditWriter::write`]).
pub fn format_line(event: &AuditEvent) -> String {
    let prival = FACILITY_LOCAL0 * 8 + event.severity.value();
    let timestamp = format_timestamp(event.tai_ns);

    let mut params: Vec<String> = Vec::new();
    let mut push = |name: &str, value: &str| {
        if !value.is_empty() {
            params.push(format!("{name}=\"{}\"", sd_escape(value)));
        }
    };
    push("commandId", &event.command_id);
    push("entity", &event.entity);
    push("class", &event.class);
    push("state", &event.state);
    push("principal", &event.principal);
    push("delegationId", &event.delegation_id);
    push("decisionId", &event.decision_id);
    push("policyHash", &event.policy_hash);

    let structured_data = if params.is_empty() { format!("[{SD_ID}]") } else { format!("[{SD_ID} {}]", params.join(" ")) };

    format!("<{prival}>1 {timestamp} - {APP_NAME} - {} {structured_data} {}", event.msg_id, event.message)
}

/// Where audit lines go -- `profiles/execution.yaml`'s (or another profile's) top-level
/// `audit:` block, [`load_profile_audit_config`]. [`Self::Disabled`] is its own variant, not
/// `Option<PathBuf>` with `None` standing in for it -- see the module doc's "When no `[audit]`
/// sink is configured" section for why this is deliberate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AuditSinkConfig {
    File(PathBuf),
    Disabled,
}

#[derive(Debug, Clone, Default, serde::Deserialize)]
struct AuditBlock {
    #[serde(default)]
    sink_path: String,
}

#[derive(Debug, Clone, Default, serde::Deserialize)]
struct ProfileDocument {
    #[serde(default)]
    audit: AuditBlock,
}

/// Reads the top-level `audit:` block out of a full profile YAML document's text. A missing
/// `audit:` key, or one with an empty (or absent) `sink_path`, parses as
/// [`AuditSinkConfig::Disabled`] -- never an error, and never a default path this module
/// invents on the profile's behalf.
pub fn load_profile_audit_config(yaml: &str) -> Result<AuditSinkConfig, serde_yaml::Error> {
    let doc: ProfileDocument = serde_yaml::from_str(yaml)?;
    Ok(if doc.audit.sink_path.is_empty() { AuditSinkConfig::Disabled } else { AuditSinkConfig::File(PathBuf::from(doc.audit.sink_path)) })
}

/// R4.2b (round 4 review defect, F2): the seam behind [`AuditWriter`] that lets a test supply
/// an arbitrary sink -- in particular, one whose every write deterministically fails -- so the
/// "the index/dispatch side effect must commit before the audit write, not after" invariant
/// `crates/av-command/src/service.rs` now documents at its one commit point
/// (`CommandAuthorityServiceImpl::append_and_commit_index`) can be tested against a *real*
/// audit-write failure rather than argued about. A `chmod` after [`AuditWriter::open`] cannot
/// produce that failure on macOS (this writer already holds an open `std::fs::File`, and a
/// permission change does not retroactively revoke an open file descriptor's own write
/// access) -- this trait is the alternative.
///
/// `pub(crate)`, deliberately: nothing outside this crate needs to implement it (only
/// [`FileSink`] below, in production, and `crate::test_support::FailingAuditSink`, in a test
/// build) -- see [`AuditWriter::from_line_sink`]'s own doc for why the constructor that takes
/// one is `pub(crate)` too, and `crate::test_support`'s own module doc for why the *failing*
/// implementor still has to live there, gated, rather than here, ungated.
pub(crate) trait LineSink: Send + Sync {
    /// Writes one already-[`format_line`]-formatted line (no trailing newline) and flushes
    /// before returning `Ok`.
    fn write_line(&self, line: &str) -> io::Result<()>;
}

/// The production [`LineSink`]: an open, append-mode file, guarded by its own `Mutex` (`write`
/// takes `&mut std::fs::File`, so this is the interior-mutability seam that lets multiple
/// concurrent [`AuditWriter::write`] callers share one `Box<dyn LineSink>` behind a shared
/// `Arc<AuditWriter>` -- matching this crate's other shared, append-only stores,
/// `crate::ledger::Ledger`). Byte-for-byte the same write sequence [`AuditWriter`] performed
/// before this seam existed: append the line plus one trailing `\n`, then flush.
struct FileSink(Mutex<std::fs::File>);

impl LineSink for FileSink {
    fn write_line(&self, line: &str) -> io::Result<()> {
        let mut file = self.0.lock().unwrap_or_else(|p| p.into_inner());
        let mut buf = line.to_string();
        buf.push('\n');
        file.write_all(buf.as_bytes())?;
        file.flush()
    }
}

/// Writes [`AuditEvent`]s as RFC 5424 lines to a configured sink. Construct once
/// ([`Self::open`]) and share (`Arc`) -- every write takes `&self`, delegating to whichever
/// [`LineSink`] this writer holds (its own internal locking, for the `File` case -- see
/// [`FileSink`]).
pub struct AuditWriter {
    sink: Option<Box<dyn LineSink>>,
}

impl AuditWriter {
    /// `Ok(Self)` with an open, append-mode file for [`AuditSinkConfig::File`] (creating the
    /// parent directory if needed, mirroring `crate::ledger::Ledger::open`'s own
    /// `create_dir_all`), or with no sink at all for [`AuditSinkConfig::Disabled`] -- see
    /// [`Self::write`] for what "no sink" then does. Behaviourally identical to before the F2
    /// `LineSink` seam existed: the file is opened the same way, and every byte
    /// [`Self::write`] produces for it is unchanged.
    pub fn open(sink: &AuditSinkConfig) -> io::Result<Self> {
        let sink: Option<Box<dyn LineSink>> = match sink {
            AuditSinkConfig::File(path) => {
                if let Some(parent) = path.parent() {
                    if !parent.as_os_str().is_empty() {
                        std::fs::create_dir_all(parent)?;
                    }
                }
                let file = OpenOptions::new().create(true).append(true).open(path)?;
                Some(Box::new(FileSink(Mutex::new(file))))
            }
            AuditSinkConfig::Disabled => None,
        };
        Ok(Self { sink })
    }

    /// F2's test-only constructor: an [`AuditWriter`] backed by a caller-supplied [`LineSink`]
    /// instead of a real file -- the only way to make [`Self::write`] fail deterministically
    /// (see [`LineSink`]'s own doc for why a `chmod`-based approach cannot). `pub(crate)`
    /// rather than `pub`: an external `tests/*.rs` integration test cannot name `LineSink` at
    /// all (it is `pub(crate)`), so it reaches this constructor only indirectly, through
    /// `crate::test_support::failing_audit_writer`/`audit_writer_failing_from` -- both `pub`,
    /// both gated `#[cfg(any(test, feature = "test-support"))]` on the module itself. Nothing
    /// about *this* constructor needs that gate (it takes no test-only type as an argument and
    /// grants no capability `open` does not already have the shape of -- an arbitrary sink is
    /// no more dangerous than an arbitrary file path), but it is `pub(crate)` anyway, on the
    /// same reasoning `crate::service`'s own private helpers use: the smallest visibility that
    /// still lets every real caller reach it.
    pub(crate) fn from_line_sink(sink: Box<dyn LineSink>) -> Self {
        Self { sink: Some(sink) }
    }

    /// Appends [`format_line`]`(event)` (plus one trailing `\n`, flushed before returning) to
    /// this writer's sink. A no-op returning `Ok(())` when this writer holds no sink (see the
    /// module doc's "When no `[audit]` sink is configured" section) -- the two cases are two
    /// explicit `match` arms, never one branch serving both.
    pub fn write(&self, event: &AuditEvent) -> io::Result<()> {
        match &self.sink {
            Some(sink) => sink.write_line(&format_line(event)),
            None => Ok(()),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use av_cdm::pb::AckLevel;

    fn transition(state: CommandState, tai_ns: i64, principal: &str, reason: &str, delegation_id: &str) -> CommandTransition {
        CommandTransition { state: state as i32, tai_ns, principal: principal.to_string(), reason: reason.to_string(), ack_level: AckLevel::Unspecified as i32, delegation_id: delegation_id.to_string() }
    }

    fn command(id: &str, entity_id: &str, class: &str) -> Command {
        Command { id: id.to_string(), entity_id: entity_id.to_string(), command_class: class.to_string(), ..Command::default() }
    }

    /// Cross-checked against `date -u -r 0` (`1970-01-01 00:00:00 UTC`) and
    /// `date -u -r 1760000000` (`2025-10-09 08:53:20 UTC`) on this host.
    #[test]
    fn format_timestamp_matches_known_reference_dates() {
        assert_eq!(format_timestamp(Tai::from_utc_nanos(0).as_nanos()), "1970-01-01T00:00:00.000000Z");
        assert_eq!(format_timestamp(Tai::from_utc_nanos(1_760_000_000_000_000_000).as_nanos()), "2025-10-09T08:53:20.000000Z");
    }

    #[test]
    fn format_timestamp_truncates_nanoseconds_to_six_fractional_digits() {
        let tai_ns = Tai::from_utc_nanos(1_760_000_000_123_456_789).as_nanos();
        assert_eq!(format_timestamp(tai_ns), "2025-10-09T08:53:20.123456Z", "the trailing 789 ns must be truncated, not rounded");
    }

    #[test]
    fn sd_escape_escapes_backslash_quote_and_close_bracket() {
        assert_eq!(sd_escape(r#"a"b\c]d"#), r#"a\"b\\c\]d"#);
        assert_eq!(sd_escape("plain"), "plain");
    }

    #[test]
    fn format_line_for_a_successful_transition_is_exact() {
        let command = command("cmd-1", "sat-1", "mode");
        let transition = transition(CommandState::Authorized, Tai::from_utc_nanos(1_760_000_000_000_000_000).as_nanos(), "operator-1", "authorize: command_class=\"mode\" via=role=\"operators\" mfa=not_required (crate::authz)", "");
        let event = event_for_transition(&command, &transition, None);
        let line = format_line(&event);
        assert_eq!(
            line,
            "<134>1 2025-10-09T08:53:20.000000Z - av-command - AUTHORIZED [avCommand@32473 commandId=\"cmd-1\" entity=\"sat-1\" class=\"mode\" state=\"AUTHORIZED\" principal=\"operator-1\"] authorize: command_class=\"mode\" via=role=\"operators\" mfa=not_required (crate::authz)"
        );
    }

    #[test]
    fn format_line_for_a_refusal_uses_warning_severity_and_refused_msgid() {
        let event = event_for_refusal(Tai::from_utc_nanos(1_760_000_000_000_000_000).as_nanos(), "cmd-2", "sat-1", "mode", "", "", "authorize: role gate refused -- none of groups [] is a role granting command_class \"mode\" (crate::authz, deny-by-default: an unlisted role, or a role that does not list this class, is refused)");
        let line = format_line(&event);
        assert_eq!(
            line,
            "<132>1 2025-10-09T08:53:20.000000Z - av-command - REFUSED [avCommand@32473 commandId=\"cmd-2\" entity=\"sat-1\" class=\"mode\" state=\"REFUSED\"] authorize: role gate refused -- none of groups [] is a role granting command_class \"mode\" (crate::authz, deny-by-default: an unlisted role, or a role that does not list this class, is refused)"
        );
    }

    #[test]
    fn format_line_includes_decision_id_and_policy_hash_only_when_present() {
        let command = command("cmd-3", "sat-1", "mode");
        let transition = transition(CommandState::Checked, 0, "policy", "decision_id=abc policy_hash=def allow=true", "");
        let decision = PolicyDecision { decision_id: "abc".to_string(), allow: true, policy_hash: "def".to_string(), reasons: vec![], matched_rule_path: "data.altavista.authority.allow".to_string(), evaluated_tai_ns: 0, input: None };
        let with_decision = format_line(&event_for_transition(&command, &transition, Some(&decision)));
        assert!(with_decision.contains("decisionId=\"abc\""), "{with_decision}");
        assert!(with_decision.contains("policyHash=\"def\""), "{with_decision}");

        let without_decision = format_line(&event_for_transition(&command, &transition, None));
        assert!(!without_decision.contains("decisionId="), "{without_decision}");
        assert!(!without_decision.contains("policyHash="), "{without_decision}");
    }

    fn tmp_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("av-command-audit-test-{name}-{}.log", std::process::id()))
    }

    #[test]
    fn audit_writer_appends_the_exact_line_plus_one_newline_to_the_configured_file() {
        let path = tmp_path("write-exact");
        let _ = std::fs::remove_file(&path);
        let writer = AuditWriter::open(&AuditSinkConfig::File(path.clone())).unwrap();

        let command = command("cmd-1", "sat-1", "mode");
        let transition = transition(CommandState::Proposed, 0, "model-x", "proposed via CommandAuthorityService.Propose", "");
        writer.write(&event_for_transition(&command, &transition, None)).unwrap();

        let contents = std::fs::read_to_string(&path).unwrap();
        assert_eq!(contents, format!("{}\n", format_line(&event_for_transition(&command, &transition, None))));

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn audit_writer_appends_across_multiple_writes_without_truncating() {
        let path = tmp_path("append");
        let _ = std::fs::remove_file(&path);
        let writer = AuditWriter::open(&AuditSinkConfig::File(path.clone())).unwrap();

        let command = command("cmd-1", "sat-1", "mode");
        for (state, tai_ns) in [(CommandState::Proposed, 0), (CommandState::Checked, 1)] {
            let transition = transition(state, tai_ns, "p", "r", "");
            writer.write(&event_for_transition(&command, &transition, None)).unwrap();
        }

        let contents = std::fs::read_to_string(&path).unwrap();
        assert_eq!(contents.lines().count(), 2);

        let _ = std::fs::remove_file(&path);
    }

    /// **When no `[audit]` sink is configured**: `write` is a no-op returning `Ok(())`, and no
    /// file is ever created.
    #[test]
    fn a_disabled_sink_is_a_no_op_that_creates_no_file() {
        let path = tmp_path("disabled");
        let _ = std::fs::remove_file(&path);
        let writer = AuditWriter::open(&AuditSinkConfig::Disabled).unwrap();

        let command = command("cmd-1", "sat-1", "mode");
        let transition = transition(CommandState::Proposed, 0, "p", "r", "");
        writer.write(&event_for_transition(&command, &transition, None)).expect("a disabled sink's write must still return Ok");

        assert!(!path.exists(), "a disabled sink must create no file at all");
    }

    #[test]
    fn load_profile_audit_config_reads_a_configured_sink_path() {
        let yaml = "audit:\n  sink_path: var/log/av-command/audit.log\n";
        assert_eq!(load_profile_audit_config(yaml).unwrap(), AuditSinkConfig::File(PathBuf::from("var/log/av-command/audit.log")));
    }

    #[test]
    fn load_profile_audit_config_with_no_audit_block_is_disabled() {
        assert_eq!(load_profile_audit_config("planes:\n  ai: {}\n").unwrap(), AuditSinkConfig::Disabled);
    }

    #[test]
    fn load_profile_audit_config_with_an_empty_sink_path_is_disabled() {
        assert_eq!(load_profile_audit_config("audit:\n  sink_path: \"\"\n").unwrap(), AuditSinkConfig::Disabled);
    }
}
